host/Capture/DXGI.cpp, host/Capture/DXGI.h, host/Capture/NvFBC.cpp, host/Capture/NvFBC.h, host/CaptureFactory.h, host/CrashHandler.h, host/ICapture.h, host/IVSHMEM.cpp, host/IVSHMEM.h, host/Makefile, host/Service.cpp, host/Service.h, host/main.cpp
Some changes that enable building of the host app using mingw-w64. I don't have VS to test building in Windows but it still should work?
Haven't tried compiling with nvfbc, and added a define to leave it out. Maybe we could add the headers in the `vendor` folder?
Note: the newer DXGI interfaces don't seem to be included in the latest released version of mingw-w64. On Arch you can install `mingw-w64-headers-git` and `mingw-w64-crt-git` from AUR to get them.
=> Windows host app Makefile

client/main.c
This PR adds the option for a borderless fullscreen window.
This allows the window to display over UI elements such as the Gnome 3 top bar.
In the case of Gnome 3, the window will display at full resolution with this option, instead of shrinking the window to fit within the space below the top bar.
Currently this option can be specified by `-F` on the command line.
=> Add borderless fullscreen option

client/main.c
Under Gnome 3 when switching to another desktop the client will be minimized and when swithing back to that desktop I have to do a quick alt-tab to bring the client back to focus and fullscreen. This pull request should fix that.
=> Do not minimize fullscreen window on focus loss

client/ivshmem/ivshmem.c
While the function `ivshmem_wait_irq` makes use of the select(3)
function, it does not include <sys/select.h>. This happens to work on
glibc based systems, which include thet file transitively via other
header files. But on musl libc based systems, this breaks compilation.
Directly include <sys/select.h> to fix the problem.
=> [client] ivshmem: fix missing <sys/select.h> include

host/Capture/NvFBC.cpp, host/Util.h
The code that's there now is re-implementing what LoadLibrary does internally under Wow64. The ifdef for `NVFBC_LIBRARY_NAME` is the only thing that's actually needed.
=> [host] simplify dll loading

host/Capture/NvFBC.cpp, host/Util.h
Reverts gnif/LookingGlass#19
While this code may seem to be useless it helps prevent abuse by wrapping the NVIDIA capture DLL to bypass the NVIDIA Capture API License Agreement.
=> Revert "[host] simplify dll loading"

host/Capture/NvFBC.cpp, host/Makefile, host/Util.h
Fixes to get the NvFBC capture driver compiling on Linux. `make -C host CONFIG_CAPTURE_NVFBC=1`
Note: Requires extracting the `NvFBC` headers from the `inc` directory of the capture SDK into the `vendor` folder. The particular header also has `Windows.h` incorrectly cased and needs adjustment there. It would be nice if we could just include it in the repo, or rewrite it if there are copyright concerns about using it verbatim, but I'll leave that out for now.
=> NvFBC on mingw

client/main.c
The SPICE protocol only supports a standard 3 button PS/2 virtual mouse. Right now SDL is passing through mouse 4/5 + which SPICE is interpreting as scroll up / down. Drop these events to avoid weird scrolling on mouse 4/5.
=> Ignore SDL_MOUSEBUTTONDOWN events incompatible with SPICE

client/utils.h
When compiling without `-DATOMIC_LOCKING=1`, it needs to include SDL headers to use the mutexes.
=> [client] fix SDL mutex compile errors

client/main.c
Moves the sleep so that it (only) gets hit when there are no events in the queue. Previously it would only throttle events after they occur, which is rare and had no impact on the 100%+ cpu usage.
=> [client] fix event loop sleep

host/Capture/DXGI.cpp, host/Capture/DXGI.h, host/Capture/NvFBC.cpp, host/Makefile, host/Service.cpp, host/Util.h
Not sure if you'd want to merge this as-is, I can split it up into a few commits if it makes sense to do so. The main issue here is that mingw headers are missing some of the newer media foundation APIs.
Also `min` was moved out of the util header because `#define min` conflicts with some libc/libstdc++ headers if they're included after it. Might be nice to just define a `LG_MIN` if it's needed in multiple parts of the code?
=> [host] mingw-w64 compile fixes

host/Makefile
Pass -DUNICODE as a CFLAG.  The visual studio project asks for
a unicode (wide-string) build, but the unix makefile did not, and
so the compiler was trying to bring the ansi functions instead
of the wide functions.
This fixes the build on MSYS2 with `make --eval=PREFIX=`.
```
Service.cpp: In member function 'bool Service::Initialize(ICapture*)':
Service.cpp:99:67: error: cannot convert 'const wchar_t*' to 'LPCSTR {aka const char*}' for argument '4' to 'void* CreateEventA(LPSECURITY_ATTRIBUTES, WINBOOL, WINBOOL, LPCSTR)'
m_cursorEvent  = CreateEvent (NULL, FALSE, FALSE, L"CursorEvent");
```
=> [host] ask for unicode with mingw-w64 makefile

client/main.c
This has been bothering me for a while, now that a11 is out decided to jump in and get it fixed.
I have a 1080p server and a 2160p client, so when using fullscreen mode small mouse movements get rounded down to zero across spice, making movements quite erratic.
To solve that, I added a simple mouse movement accumulator, whatever movement is too small to get sent to the server is kept for the next movement. Final result is smooth cursor movement independent of scaling.
=> Fixing scaled mouse movement

client/main.c
This is a feature I'd really appreciate having, so I went ahead and implemented it.
It turns out you need a window hint `SDL_HINT_GRAB_KEYBOARD` for `SDL_SetWindowGrab` to actually grab the keyboard.
From [the wiki page](https://wiki.libsdl.org/SDL_SetWindowGrab) it seems `SDL_SetWindowGrab` should also grab the mouse, but it didn't seem to do so when I tested it.
I've kept both that function call and `SDL_SetRelativeMouseMode`, despite `SDL_SetRelativeMouseMode` seeming to call `SDL_SetWindowGrab`.
`-G` option disables the keyboard grabbing
=> [client] Allow keyboard capture (#26)

client/main.c
* Since LG is now using SDL2, the SDL_VIDEODRIVER must be set for wayland.
* This fixes SDL error 'Couldn't find matching GLX visual' when creating the window.
=> [client] Adds back support for wayland

client/main.c
Minimal systems in cases may not have XDG_SESSION_TYPE set at all, causing the program to segfault at the `strcmp`. This commit sets XDG_SESSION_TYPE to `unspecified` (according to https://www.freedesktop.org/software/systemd/man/pam_systemd.html) if it is not defined in the environment.
=> [client] Fix segfault when envar XDG_SESSION_TYPE isn't set

client/main.c
The SDL resize event only gets fired when the window is resized from it's starting size, so if the user doesn't resize the window, then no size will ever be recorded into the state.
Without a size in place there both the OpenGL and the EGL renderer seem to break, though in different ways - OpenGL crashes with a glGenBuffer error (#101 #107), and EGL simply renders a black screen.
This reads the window size initially as well as on resizes, and fixes said issues at least on my system.
=> Store the initial window size in the state

client/spice/spice.c, client/spice/spice.h
so that ports >32767 get displayed correctly,
also signed overflow is undefined behaviour
Signed-off-by: Dominik Csapak <d.csapak@proxmox.com>
=> change spice port type to unsigned short

client/spice/spice.c
SPICEC_ERROR_CODE_xxx constants are supposed to be used by old
client (obsoleted years ago).
SpiceLinkReply error field uses SPICE_LINK_ERR_xxx enumeration
constants.
Signed-off-by: Frediano Ziglio <fziglio@redhat.com>
=> [client] spice: use correct enumeration for SpiceLinkReply

client/main.c
Make sure glViewport gets called as soon as we know the window
dimensions, otherwise nothing gets rendered until KVMFR communication is
established (mostly the splash).
Without the fix, './looking-glass-client -s' behaves differently than
'./looking-glass-client -s -F' in that the latter triggers a
SDL_WINDOWEVENT_SIZE_CHANGED and updates the viewport immediately after
window creation while the former doesn't and all rendering is delayed
until the frameThread successfully decodes the first frame.
As all the possible ways of updating the viewport (window creation,
window size change, frame size change) are covered with
updatePositionInfo(), the 'started' state becomes redundant and is
removed.
Note: this might be the wrong way to fix it (possible driver bug?),
glViewport's specification …
=> [client] update viewport size after window is created

client/main.c
When one need to access more than one VM simultaneously through multiple instances of Looking Glass on the same host, currently it's difficult to tell from the window title alone as they'll all be the same.
I'd think it'd be nice to add an option so that the end user could set their own window title (either through the config file or scripting) - this should make it easier for the user to tell which VM they're using.
=> [client] Added option for custom window title

c-host/platform/Windows/src/platform.c, host/IVSHMEM.cpp, host/IVSHMEM.h, host/Service.cpp, host/Service.h, host/main.cpp
Device selection on `c-host` is very simple at the moment. It would be possible to extend it to specify ivshmem devices not only by member index, but also by pci bus location (bus, slot and optional function)
=> Added support for IVSHMEM device selection on old `host` and new `c-host` for windows

module/Makefile, module/dkms.conf
Update to allow the module to be build for different kernels. Needed for DKMS.
Also updated the DKMS file to make use of that.
I've not made other changes to the DKMS file  (such as removing the REMAKE_INITRD and changing the module location) as I do not know what system the file was originally targeting and if that actually does need those.
=> KVMFR Module build file update

client/README.md, client/src/config.c, client/src/main.c, client/src/main.h
Default behavior is not changed - not configuring these options unfocused window is minimized.
* Added short option -N (default false).
* Added config entry win:noMinimizeOnFocusLoss (default false).
=> Implement option to disable minimizing window on focus loss

client/src/config.c, client/src/main.c
Added changes to config.c and main.c to support the ability auto-detect the monitor refresh rate which is then doubled for the purpose of the FPS Limit.
=> Auto Detect Monitor Refresh Rate

client/src/main.c
According to client/src/config.c#183 the default value for `minimizeOnFocusLoss` is `true`, also `SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS` only works on fullscreen, so by using `params.fullscreen || !params.minimizeOnFocusLoss` the application window was never able to minimize on losing focus (not even if `win:minimizeOnFocusLoss=yes` was used).
With this change, the `minimizeOnFocusLoss` flag will be correctly applied thus the window will minimize by default when it loses focus (when running on fullscreen).
Please let me know if it is preferred to not minimize by default so I can toggle the flag and update the readme.
=> Respect minimizeOnFocusLoss

client/renderers/EGL/egl.c
[Why]
Recent versions of Mesa may have trouble with surface creation, resulting in
errors like:
egl.c:428  | egl_render_startup             | Failed to create EGL surface (eglError: 0x300b)
[How]
Replace eglGetDisplay() with eglGetPlatformDisplay(). Requires EGL 1.5, but should
be supported with any desktop driver released in the past few years.
I haven't tested with Wayland but it should be correct.
=> [client] Use eglGetPlatformDisplay() to fix surface creation

client/spice/src/spice.c
Returning -1 from a function with bool as return argument is the same as
returning true. If the channel is not connected, return false instead to
indicate the error.
=> [client] fix return value in spice_read_nl error path

common/src/platform/linux/crash.c
binutils has changed several macros. Added ifdef to allow building with
stable and bleeding edge versions.
refs #232
=> [common] fix build for newer versions of binutils

client/README.md, client/src/main.c, client/src/main.h
Adds a <kbd>ScrLk</kbd>+<kbd>Q</kbd> keybind to conveniently quit the client.
On a side note, I noticed that all the keybinds are in `release_key_binds()` except for the mouse sensitivity ones. Is this intentional, or an oversight?
=> [client] add quit keybind

client/renderers/EGL/egl.c
"Multsampling" to "Multisampling"
=> [client] egl: typo fix in info message

client/src/config.c, client/src/main.c, client/src/main.h
Adds the option spice:captureOnStart which automatically captures keyboard and mouse input when Looking Glass starts. Defaults to false in order to maintain current default behavior.
This allows for the creation of a single keyboard shortcut which launches Looking Glass in full screen mode and automatically captures input (equivalent functionality to pressing the button on a physical KVM switch). Previously a shortcut could be created to launch Looking Glass, but you still had to press scroll lock (or whatever the escape key has been mapped to) to begin capturing input.
=> [client] add option to capture input on start

common/src/platform/linux/CMakeLists.txt, common/src/platform/linux/time.c
This adds the missing timer implementation for linux (#276).
~~There were also a couple of unrelated compilation issues for the linux host (missing headers and libraries), which are also fixed.~~
=> Added linux timers

host/README.md, host/installer/installer.nsi
Fixes: #277 
Todo-
Later possibilities- 
- Full banner instead of an icon in the installation window. Requires said banner to be created.
- Install `IVSHMEM` driver. Requires investigation about redistribution of RedHat signed builds.
- Put a readme in the install directory.
- Integrate with cmake. Decided to not do this yet, I could not get the cpack nsis module working.
Requires input from @gnif -
--- 
The only build requirement is nsis. Requires `looking-glass-host.exe` to exist in `c-host/build/`
Can be built with `makensis /path/to/installer.nsi`.
=> [Host] Add NSIS installer

client/README.md
Option is from #278 and already merged, but the PR didn't update the readme for the client.
=> Add spice:captureOnStart to client readme

client/src/main.c, client/src/main.h
I'm pretty confident this won't mess anything up, and I cleaned it up to be acceptable.
=> Fix issues blocking Clang-built LookingGlass

client/README.md, client/src/config.c, client/src/main.c, client/src/main.h
Adds the option spice:alwaysShowCursor which prevents Looking Glass from hiding the host cursor when leaving the window. Defaults to false in order to maintain current default behavior.
This allows use of both SPICE input as well as a directly connected (pass-through) mouse for use cases where both ease of use through SPICE is required and low-latency without restarting the client. As a side effect, it also provides compatibility with Barrier/Synergy.
Closes #321
=> [client] add option to always show cursor

client/README.md, client/renderers/EGL/egl.c, client/renderers/OpenGL/opengl.c, client/src/main.c
eglSwapBuffers is allowed to block when called with a nonzero interval
parameter. On Wayland, Mesa will block until a frame callback arrives.
If an application is not visible, a compositor is free to not schedule
frame callbacks (in order to save CPU time rendering something that is
entirely invisible).
Currently, starting Looking Glass from a terminal, hiding it
entirely, and sending ^C will cause Looking Glass to hang joining the
render thread until the window is made visible again.
Calling eglDestroySurface is insufficient to unblock eglSwapBuffers, as
it attempts to grab the same underlying mutex.
Instead, this PR makes it so that we pass a 0 interval to
eglSwapBuffers when running on Wayland, such that we don't block waiting
for a frame callback. This is not entirely ideal as it …
=> Fix hang in eglSwapBuffers when exiting while not visible

client/renderers/EGL/egl.c
This commit makes Looking Glass always use the OpenGL renderer when
running on Wayland. The EGL renderer is broken on Wayland and can't
reasonably be fixed until SDL is dropped entirely (as per
https://github.com/gnif/LookingGlass/issues/306).
Until that time, the OpenGL renderer provides a much better
Wayland-native experience.
=> [client] egl: disable EGL when running on Wayland

client/renderers/OpenGL/opengl.c
For some reason, if we don't ask for 8-bit, wayland will give a context with
lower bit depth, which looks terrible.
=> [client] opengl: require 8 bit colour when creating context

client/src/main.c
Some setups (e.g. Wayland) have high precision scroll wheel input, such
that the y-delta on an event may exceed 1. In these cases, scrolling up
currently gets treated as scrolling down.
This commit changes the checks to use > 0 rather than == 1.
This is the approach suggested in
https://wiki.libsdl.org/SDL_MouseWheelEvent.
=> [client] spice: properly handle high-precision scroll wheel input

client/src/main.c
On Wayland, SDL_WINDOWEVENT_CLOSE is sent even when exiting with keyboard
shortcuts. This meant that the client is still closed even with -Q.
We now swallow SDL_WINDOWEVENT_CLOSE if the cursor is inside the VM. This
should prevent keyboard shortcuts from closing the client, while still
allowing the window to be closed by clicking X with the mouse per #138.
=> [client] fix ignoreQuit on Wayland

client/src/main.c
The hint "SDL_HINT_VIDEO_ALLOW_SCREENSAVER" only works if set before SDL_Init(). Move it to the proper location.
SDL_EnableScreenSaver doesn't work at all here and seems to be targeted towards mobile platforms. Tested to work with DPMS monitor suspends and -S properly overrides it.
=> [client] fix screensaver enable

client/src/main.c
`sizeof(struct Foo())` is always 1, because it's treated as the type of a function returning a `struct Foo`, and functions are size 1.
```
==================================================================
==7680==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000ec010 at pc 0x5622fcf9f386 bp 0x7f36084ff680 sp 0x7f36084ff678
WRITE of size 4 at 0x6020000ec010 thread T1
#0 0x5622fcf9f385 in clipboardRequest /code/LookingGlass/client/src/main.c:707
#1 0x5622fd0036c9 in wayland_cb_notice /code/LookingGlass/client/clipboards/Wayland/src/wayland.c:521
#2 0x5622fcf9f4dc in spiceClipboardNotice /code/LookingGlass/client/src/main.c:724
#3 0x5622fcfc4d59 in spice_agent_process /code/LookingGlass/repos/PureSpice/src/spice.c:1106
#4 0x5622fcfc16d6 in spice_on_main_channel_read …
```
=> [client] clipboard: fix heap-buffer overflow in clipboardRequest

client/src/wm.c
Tiny fixup preventing the cursor from ever being released in the fallback branch.
=> [client] wm: specify SDL_FALSE to SDL_SetWindowGrab in wmUngrabPointer

client/src/main.c
Use different logic on Wayland to avoid warp. This requires a 1:1 mouse movement patch in the guest (when using Wayland), but it makes the desktop usable. For gaming, capture mode is recommended.
=> Add Wayland-specific mouse logic due to lack of warp

client/CMakeLists.txt, client/src/main.c, client/src/main.h, client/src/wm.c, client/src/wm.h
This patch series removes SDL from the grabbed mouse handling path on Wayland.
Some build infra changes are necessary to build unstable Wayland protocols `relative-pointer-unstable-v1` and `pointer-constraints-unstable-v1-client-protocol`. These protocols have ~universal adoption, and are what SDL uses internally too.
I've attempted to cleanly separate the Wayland bits through an opaque pointer, in hopes that this will make it easy to move into ADL later.
This PR likely still contains bugs, but I'm dogfooding it for now.
=> Implement relative mouse mode for Wayland

client/CMakeLists.txt, client/src/main.c, client/src/wm.c
This patch uses the `keyboard-shortcuts-inhibit-unstable-v1` Wayland protocol to inhibit all window manager keyboard shortcuts, effectively grabbing the keyboard.
=> [client] wm/wayload: implement keyboard grabbing

client/src/main.c
In the previous commit, the wrong variable was updated.
=> [client] spice/wayland: correctly update guest cursor location

client/src/main.c
This will now correctly respect the cursor hotspot and scaling. It will also avoid division by zero when `dpiScale` is not initialized.
=> [client] spice/wayland: fix multiple mouse issues

client/CMakeLists.txt, client/clipboards/CMakeLists.txt, client/clipboards/Wayland/CMakeLists.txt, client/clipboards/Wayland/src/wayland.c, client/clipboards/X11/src/x11.c, client/src/main.c, client/src/wm.c, client/src/wm.h
=> [client] add Wayland clipboard support

client/src/main.c, client/src/main.h, client/src/wm.c
Depends on https://github.com/gnif/LookingGlass/pull/353 for conflict reasons, but only the last commit in this chain has changes.
=> [client] wm/wayland: bypass SDL loop for pointer events

client/src/wm.c
When input:grabKeyboardOnFocus is set (default), entering capture mode grabs
the keyboard a second time. This commit makes the second grab a no-op on
Wayland to avoid a crash.
=> [client] wm/wayland: correctly handle double keyboard grab

client/clipboards/Wayland/src/wayland.c
This prevents looking-glass-client from failing with an error message like:
error marshalling arguments for receive (signature sh): null value passed for arg 0
Error marshalling request: Invalid argument
=> [client] clipboard/wayland: fix null mimetype receive error

client/clipboards/Wayland/src/wayland.c
Wayland requires us to set all listeners, even for events we don't care
about. Not doing so caused Looking Glass to abort when used as a drop
target.
=> [client] clipboard/wayland: make DnD a no-op

client/CMakeLists.txt
This PR adds support for building with UBSan. Running with it enabled currently does produce errors, but I will address those separately.
=> [client] add support for compiling with UndefinedBehaviorSanitizer

client/CMakeLists.txt, client/renderers/OpenGL/opengl.c, client/src/main.c
-Wno-sign-compare is used to suppress warnings related to comparing signed
values with unsigned ones. It's too pedantic.
-Wunused-parameter is also too pedantic, especially since all parameters
have to be named in C.
Otherwise, -Wextra lets us catch bugs, such as x < 0 for unsigned x.
On gcc, we pass -Wimplicit-fallthrough=2 so it will recognize our fall
through comment. Braces had to be removed in one instance so
that gcc can recognize the fallthrough comment correctly.
This should be merged after gnif/PureSpice#5.
=> [client] Build with -Wextra and fix errors

client/src/main.c
The prototype for abs is int abs (int n), which implicitly casts floating
point values to integers. The correct function is fabs.
This commit allows the client to compile under clang.
=> [client] spice: correctly use fabs for floating point

host/platform/Windows/src/service.c
The handles in PROCESS_INFORMATION must be closed if not used, or they
will leak.
=> [host] windows: avoid leaking process and thread handles

host/platform/Windows/src/service.h
The host process will be changed to return these codes, from which the
service process could decide whether to exit or restart the process and log.
Note that on Windows, return values are 32-bit unlike POSIX which is only 8.
=> [host] windows: define exit codes for future use

host/platform/Windows/CMakeLists.txt, host/platform/Windows/src/service.c
Use the process handle returned by CreateProcessAsUserA to wait on the
process. This results in faster response times and less polling.
For example, it now restarts instantly when UAC is activated.
This also removes the call to OpenProcess and rendering the mutex unnecessary.
As a bonus, it should fix #298.
=> [host] windows: improve restart logic and remove mutex hack

host/platform/Windows/src/service.c
It shouldn't have any effect, since the host application is created with
the token, and there is no need for the service itself to impersonate.
In practice, removal doesn't appear to have any effect on the ability to
capture privileged things like secure desktop.
=> [host] windows: remove ImpersonateLoggedOnUser call

host/platform/Windows/src/service.c
This makes it easier to identify when things in the logs happened.
=> [host] windows: add timestamps to service logs

host/platform/Windows/src/service.c
This should eliminate all handle leaks resulting from killing the host.
=> [host] windows: close handle to token in enablePriv

client/src/main.c
Now correctly set inView to only be within the guest and not the letterboxed
areas. Also show the system cursor in the letterboxed area.
=> [client] wayland: fix mouse logic after refactor

.github/workflows/build.yml
This will let us automatically catch issues that only one compiler wouldn't, like https://github.com/gnif/LookingGlass/pull/378.
=> Build client and obs plugin with both GCC and Clang

host/platform/Windows/src/service.c
To quote MSDN documentation:
> The lpApplicationName parameter can be NULL, in which case the executable
> name must be the first white space–delimited string in lpCommandLine. If
> the executable or path name has a space in it, there is a risk that a
> different executable could be run because of the way the function parses
> spaces. The following example is dangerous because the function will
> attempt to run "Program.exe", if it exists, instead of "MyApp.exe".
>
>   LPTSTR szCmdline[] = _tcsdup(TEXT("C:\\Program Files\\MyApp"));
>   CreateProcessAsUser(hToken, NULL, szCmdline, /*...*/ );
>
> If a malicious user were to create an application called "Program.exe" on
> a system, any program that incorrectly calls CreateProcessAsUser using the
> Program Files directory will run this …
=> [host] windows: avoid quoting issues with CreateProcessAsUserA

client/displayservers/Wayland/wayland.c, client/include/app.h, client/src/main.c
We are actually getting mouse events directly from Wayland instead of going
through SDL, so we call app_updateCursorPos in pointer motion handlers and
swallow the SDL event.
Also removed parameters for app_handleMouseBasic as it relies exclusively on
absolute positions provided by app_updateCursorPos. Wayland does not give
you relative movements at all unless grabbed and passing absolute movements
is semantically incorrect.
Note that when the cursor is grabbed, movements are handled entirely through
relativePointerMotionHandler in wayland.c and does not go through
app_handleMouseBasic at all.
=> [client] wayland: update absolute mouse position

host/platform/Windows/src/service.c
This is definitely supposed to sleep for 1 second.
1 ms is basically no throttling.
=> [host] windows: sleep for 1 second instead of 1 millisecond

client/displayservers/SDL/sdl.c, client/displayservers/Wayland/wayland.c, client/displayservers/X11/x11.c, client/include/interface/displayserver.h, client/src/main.c
`zwp_relative_pointer_manager_v1` and `zwp_pointer_constraints_v1` are
supported by GNOME/KDE/sway (and many other compositors), but they are
not a required part of the protocol.
Some users also run software in one-off nested compositors like [cage][0]
for an extra layer of isolation; cage, at least, does not support
pointer captures.
This commit makes Looking Glass warn when an optional protocol is
unsupported, and fail if a required one is missing. Pointer grab paths
have a new guard against the aforementioned protocols being missing.
[0]: https://github.com/Hjdskes/cage
=> [client] wayland: implement more graceful degradation logic

client/src/main.c
This seems like a leftover from ef678ba, but the guard already exists in
setCursorInView itself.
=> [client] mouse: remove erroneous guard for setCursorInView

client/src/main.c
Unless the corresponding mouse down event was on our surface, we should
not be receiving the mouse up.
This is always the case on Wayland. On some other platforms,
SDL_CaptureMouse can be used to obtain input that happens outside the
Looking Glass surface, but Looking Glass does not make use of that
function.
We may want to process a mouse up if the corresponding mouse down
initiated a drag (e.g., of a window) that was released slightly outside
of the Looking Glass surface. Previously, Looking Glass would ignore the
mouse up, and the guest would be confused into thinking the button had
never been released, not ending the drag.
=> [client] mouse: process mouse up event even if not in view

client/src/main.c
This avoids putting internal coordinates out of screen and causing cursor
spasms while dragging beyond the edge.
=> [client] wayland: clip desired guest cursor position

client/displayservers/Wayland/wayland.c
It appears that Wayland pointer motion handlers are called even when relative
mouse mode is enabled. The events they generate break first-person games.
This commit disables those handlers when relative mouse is enabled.
=> [client] spice/wayland: fix capture mode relative movement

client/displayservers/Wayland/CMakeLists.txt, client/displayservers/Wayland/wayland.c
This PR implements the plumbing for idle inhibition on Wayland, preventing the WM's screen locker from activating if Looking Glass has keyboard focus.
Potential (future?) improvements:
- adhere to `win:noScreensaver`; would need some more hooks from main
- query whether there is something inhibiting idle on the guest side, and only inhibiting idle on the host side if so
Note: I've checked SDL sources, and `SDL_HINT_VIDEO_ALLOW_SCREENSAVER` (used in main.c) is currently no-op on Wayland.
=> Implement idle inhibition on Wayland

client/displayservers/SDL/sdl.c, client/displayservers/Wayland/wayland.c, client/displayservers/X11/x11.c, client/include/interface/displayserver.h, client/src/main.c
This also makes Wayland idle inhibition respect noScreensaver setting.
=> [client] displayserver: move screensaver handling into displayservers

client/renderers/EGL/egl.c, client/src/main.c
Build failed with `_FORTIFY_SOURCE` enabled because the compiler couldn't ensure the switch statements didn't hit the default arm and thus wouldn't define the variables. Adding a statically failing assert makes sure that all code paths either define the variables or fail early.
```
$ cd client
$ env CFLAGS='-O1 -D_FORTIFY_SOURCE=1' cmake -B build/
$ make -C build
[...]
client/renderers/EGL/egl.c: In function ‘egl_calc_mouse_size’:
client/renderers/EGL/egl.c:299:36: error: ‘h’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
299 |         (this->mouseHeight * (1.0f / h)) * this->scaleY
|                              ~~~~~~^~~~
```
=> [client] Fix compiler warnings about potentially uninitialized variables

client/src/main.c
It does not make sense to accumulate fractional error in non-capture mode
as you know exactly where the cursor is supposed to be, at least on Wayland.
On Wayland, we base movements on the current guest position and desired
target position, and the accumulated errors only skew our movements.
=> [client] spice/wayland: fix jitter when moving the cursor slowly

host/platform/Windows/CMakeLists.txt, host/platform/Windows/capture/NVFBC/src/nvfbc.c, host/platform/Windows/include/windows/force_compose.h, host/platform/Windows/src/force_compose.c
NvFBC is unable to capture certain applications that bypasses the DWM
compositor, for example, Firefox playing video in full screen. This 
has been a known issue for a long time with Nvidia's ShadowPlay, see:
* https://www.nvidia.com/en-us/geforce/forums/geforce-experience/14/233709/                                      
* https://crbug.com/609857
Nvidia won't fix this, but there are workarounds. For example, we
create a transparent 1x1 layered window, which forces desktop composition
to be enabled.
Note that SetLayeredWindowAttributes also supports alpha-based transparency,
but setting transparency to 0 will cause DWM to skip composition. We could 
use a transparency of 1, but this ruins the image by the slightest bit, 
which is unacceptable. Therefore, we must use chroma key-based …
=> [host] nvfbc: force composition to capture some full screen apps

client/src/main.c
Namely, we should inhibitIdle if noScreensaver is true, not the other way
around.
=> [client] wm: use correct logic for screensaver inhibition

client/displayservers/Wayland/wayland.c
We are forced to use accelerated movement in regular mode as that is how the
host machine cursor moves and we want the cursors to line up (since Wayland
cannot do warps). To avoid a change in sensitivity when toggling capture
mode on/off, we should use accelerated deltas for capture mode as well,
unless the user explicitly asks for raw input with input:rawMouse.
=> [client] wayland: use acceleration in capture mode unless rawMouse

host/platform/Windows/capture/NVFBC/src/nvfbc.c
This is because we keep track of the top-left corner of the cursor, not
the location of the hotspot. When the cursor shape changes, the hotspot
location may also change. When it does, the position of the top-left
corner changes and requires an update.
In the case that we do not have the current cursor position, which     
happens on startup, we do not generate the update.
=> [host] nvfbc: update cursor position on shape change

host/platform/Windows/src/service.c
Before this change, the log is buffered, so if the host application exits
for any reason, it usually would not show up in the log file immediately,
and the service has to be restarted for the logs to be flushed.
This commit disables the buffering so that any log entries shows up
immediately.
=> [host] service: disable buffering on the log file

client/src/main.c
Under some circumstances, Looking Glass can hang when SIGINT'd, for
instance, if it's stuck waiting on spice I/O that won't complete because
the guest is misbehaving.
This commit provides an escape hatch for such cases, so one doesn't have
to reach for `kill -9 $(pidof looking-glass-client)`.
=> [client] unconditionally quit on second SIGINT

common/src/platform/windows/CMakeLists.txt, common/src/platform/windows/crash.c
This commit uses the DbgHelp library which is shipped with Windows to
generate stack traces with function names and line number information.
It takes advantage of the pdb file generated by cv2pdb that is now
installed with looking-glass-host.exe.
Example output from reverting the NvFBC fixes:
```
407818761245 [E]              crash.c:86   | exception_filter               | ==== FATAL CRASH (B3-rc1-20-g8de5386bd5+) ====
407818761664 [E]              crash.c:88   | exception_filter               | exception 0xc0000005 (ACCESS_VIOLATION), address is 0000000000411784
407818808932 [E]              crash.c:130  | exception_filter               | [trace]:  1: C:\Program Files\Looking Glass (host)\looking-glass-host.exe:lgSignalEvent+0x4 …
```
=> [common] windows: implement crash handler for stack traces

client/displayservers/SDL/sdl.c, client/displayservers/Wayland/CMakeLists.txt, client/displayservers/Wayland/wayland.c, client/displayservers/X11/x11.c, client/include/app.h, client/include/interface/displayserver.h, client/renderers/EGL/egl.c, client/renderers/EGL/shader/desktop_rgb.frag, client/renderers/EGL/shader/splash_bg.frag, client/renderers/EGL/shader/splash_bg.vert, client/renderers/EGL/shader/splash_logo.frag, client/renderers/EGL/shader/splash_logo.vert, client/renderers/EGL/splash.c, client/src/app.c
This PR implements window creation logic and handlers for window events. When merged, the egl backend should mostly work on Wayland. The OpenGL backend is out of scope of this PR.
There are a few unimplemented features, such as client-side decorations (which SDL doesn't support either), disabling resize, and centring windows, but the client should be usable on Wayland.
=> Make egl backend work on Wayland post-refactor

client/displayservers/CMakeLists.txt
`$DISPLAY` will be set even in a Wayland session, which causes LG to
initialize itself under Xwayland unless it is explicitly compiled with
`-DENABLE_X11=OFF`.
We could add a Wayland check within the X11 backend, but reordering the
code-generated array seems like a better solution.
=> [client] probe Wayland backend first

host/platform/Windows/capture/NVFBC/src/nvfbc.c, host/platform/Windows/src/mousehook.c
Before this commit, the NvFBC backend only generated the first cursor
position update when the mouse moves. Therefore, if the user does
not move the mouse, the cursor will be shown at (0, 0), which is not
ideal.
This commit changes this behaviour to unconditionally generate a
cursor update when the mouse hook initializes.
=> [host] nvfbc: generate cursor position update on startup

client/CMakeLists.txt, client/displayservers/SDL/sdl.c, client/displayservers/Wayland/wayland.c, client/displayservers/X11/x11.c, client/include/app.h, client/include/interface/displayserver.h, client/src/app.c
This PR basically borrows the context creation code from the EGL backend to create OpenGL contexts on Wayland, since that is the only supported way to do so. I also made OpenGL support code optional.
This supersedes #427.
=> Implement OpenGL backend for Wayland

client/displayservers/Wayland/wayland.c
We used to test for the EGL_KHR_platform_base and EGL_EXT_platform_base,
but those only really signal the availability of eglGetPlatformDisplay(EXT)
functions, not whether the constant EGL_PLATFORM_WAYLAND_KHR or
EGL_PLATFORM_WAYLAND_EXT is accepted by their respective functions.
Instead, we switch to test for the extensions that tells us whether the
Wayland platform is supported.
=> [client] wayland: check for the Wayland platform extension

client/displayservers/Wayland/wayland.c, client/include/app.h, client/src/app.c, client/src/main.c, client/src/main.h
One of the major issues with the old tracking code is a data race
between the cursor thread updating g_cursor.guest and the
app_handleMouseBasic function. Specifically, the latter may have
sent mouse input via spice that has not been processed by the guest
and updated g_cursor.guest, but the guest may overwrite g_cursor.guest
to a previous state before the input is processed. This causes some
movements to be doubled. Eventually, the cursor positions will
synchronize, but this nevertheless causes a lot of jitter.
In this commit, we introduce a new field g_cursor.projected, which
is unambiguously the position of the cursor after taking into account
all the input already sent via spice. This is synced up to the guest
cursor upon entering the window and when the host restarts. Afterwards,
all …
=> [client] spice/wayland: improve cursor tracking logic

.github/issue_template.md, client/src/main.c, host/README.md, host/platform/Windows/CMakeLists.txt, host/platform/Windows/installer.nsi, host/platform/Windows/src/platform.c, host/platform/Windows/src/platform.h, host/platform/Windows/src/service.c
Instead of using %windir%\Temp, which is not accessible by default and
contains a lot of unrelated files, as the location for our log files,
this PR moves it to %ProgramData%\Looking Glass (host), which will
be a dedicated directory just for the LG host log files. This applies
to both the host application logs and the service logs.
Also, we now switched to using PathCombineA from shlwapi.dll instead
of using snprintf, which greatly simplifies the code. PathCombineA
guarantees that the path would not overflow a buffer of MAX_PATH.
Finally, this PR makes the installer create a shortcut to the log directory.
=> [host] windows: move log path to %ProgramData%\Looking Glass (host)

client/displayservers/Wayland/wayland.c
Before this, copying rich text ends up with a lot of funky behaviour,
for example:
* copying text from Discord shows up as HTML unless pasted into a text
editor first
* copying text from Firefox shows up as the single letter h
This commit fixes all the above issues.
Due to the change in logic, we now use the first text format offered
instead of the last, which is almost certainly the preferred form.
Doing this gets us proper Unicode support, or Unicode characters would
end up as escapes of the form \uXXXX (this is used in the fallback
forms for applications without UTF-8 support).
=> [client] wayland: fix copying rich text into guest

host/platform/Windows/capture/NVFBC/src/nvfbc.c
mouseHook_install and dwmForceComposition both create threads, but these
are only freed in nvfbc_deinit which is not called if nvfbc_init fails.
These should be freed if the pointer thread fails to be created, as
nothing else could be cleaning it up.
=> [host] nvfbc: cleanup threads created by nvfbc_init on failure

host/platform/Windows/capture/NVFBC/src/nvfbc.c
Moving NvFBCToSysSetup to nvfbc_init means that when the pointer thread
fails to be created, NvFBCToSysRelease needs to be called.
To resolve such cleanup issues in the future, we instead call nvfbc_deinit,
which should cleanup everything that needs to be cleaned up. fails.
=> [host] nvfbc: fix resource leak when pointer thread creation fails

client/renderers/EGL/egl.c, client/renderers/EGL/help.c, client/renderers/EGL/shader/help_bg.frag
This should prevent the looking-glass-client window from having an alpha
channel. On Wayland, the alpha channel is used to compose the window onto
the desktop, so the wallpaper would bleed through unless set to complete
opaque.
We worked around this by using constant alpha for rendering, but it was
not sustainable. Instead, we should just ask for 24-bit context.
An alternative would to continue using 32-bit colour and the following
blend function:
glBlendFuncSeparate(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, GL_ZERO, GL_ONE);
This approach is implemented in #443.
=> [client] egl: create 24-bit colour context

client/src/main.c
While a compositor will never send us 0-delta motion events, they can
still end up as 0-deltas post-projection, consuming QEMU buffer space
for no reason.
This should help with mouse skipping issues.
=> [client] spice: don't send zero deltas for Wayland input

client/include/app.h, client/include/interface/renderer.h, client/renderers/EGL/egl.c, client/renderers/EGL/fps.c, client/renderers/EGL/fps.h, client/renderers/OpenGL/opengl.c, client/src/app.c, client/src/keybind.c, client/src/main.c, client/src/main.h
Before, if you want to see the FPS, you need to close the client and
restart it with the -k switch to see the FPS. This is annoying.
This PR introduces a new keybind, ScrollLock+P, which, when pressed,
toggles the display of the FPS.
This is implemented for both EGL and OpenGL backends.
=> [client] renderer: add ability to toggle the FPS display

client/src/core.c
This is a new PR based on information gained in #446.
It appears that the keyboard should only be grabbed if the client is
focused and the cursor is in the view. However, the relevant logic was
missing from core_setCursorInView, and the keyboard was never actually
grabbed.
This commit adds the call to g_state.ds->grabKeyboard(), allowing grabbing
to work.
=> [client] spice: fix input:grabKeyboardOnFocus

client/displayservers/Wayland/wayland.c
These used to be owned by SDL and can't be cleaned up. This has since
changed.
=> [client] wayland: cleanup surface and display

client/src/config.c, client/src/main.c, client/src/main.h, common/include/common/KVMFR.h, host/include/interface/platform.h, host/platform/Linux/src/platform.c, host/platform/Windows/CMakeLists.txt, host/platform/Windows/src/platform.c, host/src/app.c
In this PR, the host application is modified to detect if any application on the guest called `SetThreadExecutionState(ES_DISPLAY_REQUIRED | ES_CONTINUOUS)` to disable the screensaver and report this information to the client.
This PR also adds a new flag `win:autoScreensaver`, which when set to yes, automatically disables the screensaver on the host machine when we detect that the screensaver is disabled in the guest, and re-enables it when it is no longer disabled.
The new flag `win:autoScreensaver` conflicts with the flag `win:noScreensaver` (`-S`) and cannot be specified at the same time.
=> Automatically disable screensaver when requested in the guest

client/renderers/EGL/egl.c, client/renderers/OpenGL/opengl.c
This effectively reverts 4bceaf5.
Upstream ticket: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4180
Commit 941c651 makes working around the hang in LG itself not as
annoying as before.
In the future, we can bypass this entire issue by implementing our own
swapchain and listening to frame callbacks ourselves.
=> [client] wayland: allow EGL/OpenGL vsync to be set to on

module/README.md, module/kvmfr.c
Added an array option static_size_mb to the kvmfr module to create a
list of in-memory kvmfr devices. These devices support dmabuf just like
normal kvmfr devices. Additionally, they can be mmap'd, which allows
them to be passed to qemu as ivshmem devices.
This PR seems to work, but as someone with zero kernel experience, I don't necessarily trust it without careful review.
=> [module] support in-memory kvmfr devices

module/kvmfr.c, module/test.c, module/test.expected
This PR contains some improvements `mmap` implementations in the kvmfr module after #455.
This PR:
* implements mmaping for PCI `kvmfr` devices (not going through the `dmabuf`)
* uses more optimal implementation of `mmap` for `dmabuf`, bypassing the need to fault in the pages one by one
* improves the test program to catch offset handling issues in the `mmap` implementations
* provides sample correct output for the test program
=> [module] improvements after adding in-memory devices

client/renderers/EGL/texture.c
This commit forces the DMA'd memory to be copied into the texture in
the EGL on_frame handler. This avoids tearing when the LG host inevitably
updates the underlying memory. We need an additional copy inside the GPU,
but this is cheap compared to copying from system memory.
We could have used logic to lock the memory buffer, but that would require
performing DMA on every frame, which wastes memory bandwidth. This
manifests as reduced frame rate when moving the mouse compared to the
non-DMA implementation.
We also keep multiple EGLImages, one for each DMA fd, to avoid issues
with the OpenGL driver.
=> [client] egl: force DMA copy into texture in on_frame

client/src/main.c
When input:grabKeyboardOnFocus=no, exiting capture mode should ungrab
the keyboard. Otherwise, focusing the window doesn't grab the keyboard,
but toggling capture mode would leave the keyboard stuck in a grabbed
state until defocused.
=> [client] spice: correctly ungrab keyboard when grabKeyboardOnFocus=no

client/displayservers/Wayland/wayland.c, common/CMakeLists.txt, common/include/common/countedbuffer.h, common/include/common/locking.h, common/src/countedbuffer.c
This PR implements asynchronous clipboard reads/writes.
To achieve this, it converts `waylandWait` to use `epoll(7)` and enables the registration and deregistration of additional file descriptors to wait for in the event loop. This machinery would be used for clipboard reads/writes.
With asynchronous operations came more opportunity for race conditions:
* A new clipboard offer may be received while we are handling the current one. We handle this by cancelling the current read and attempting to read the new clipboard offer.
* Multiple Wayland clients may request clipboard data, so we support multiple simultaneous outgoing transfers.
* Our clipboard data source may be cancelled while there are ongoing transfers. We continue those transfers until they are finished.
Since we need to continue …
=> [client] wayland: implement asychronous clipboard read/writes

client/README.md, client/src/app.c, client/src/config.c, client/src/main.h
This makes dealing with window manager shortcuts that overlap with guest
keys more pleasant, while retaining the previous functionality for users
who prefer it.
For instance, previously, using Alt+Tab (or $mod as Alt in i3/sway
movement commands) would result in the guest retaining Alt as pressed.
When the guest regained focus, it would continue thinking Alt is
pressed, leading to accidentally triggering obscure shortcuts. One had
to remember to press Alt again to "unstick" things, which was
suboptimal.
=> [client] input: add releaseKeysOnFocusLoss option

client/renderers/OpenGL/CMakeLists.txt, client/renderers/OpenGL/opengl.c
We only use gluOrtho2D, which is trivially replaced with glOrtho, and
gluErrorString which can be replaced with a small lookup table.
=> [client] opengl: remove glu dependency

client/README.md, client/displayservers/SDL/sdl.c, client/displayservers/Wayland/wayland.c, client/displayservers/X11/x11.c, client/include/interface/displayserver.h, client/src/core.c, client/src/main.c
As it turns out, pointer confines can be used to warp cursors on the same surface on Wayland. This PR implements warps with this.
This may not necessarily work for all compositors. As such, the old cursor routines are still kept, and used when `wayland:warpSupport=no`.
This code is currently only tested to work on sway. Interested users should test this branch on Mutter and KWin and report findings.
=> [client] ds: implement Wayland warp support

client/renderers/EGL/desktop.h, client/renderers/EGL/egl.c, client/renderers/EGL/egldebug.c, client/renderers/EGL/model.c, client/renderers/EGL/shader.c, client/renderers/EGL/texture.c, client/renderers/EGL/texture.h
After this PR, EGL functions are now accessed through <EGL/egl.h>
instead of through <SDL2/SDL_egl.h>, removing a pointless dependency
on SDL.
=> [client] egl: remove dependency on SDL

module/kvmfr.c
It appears that the PCI BAR memory is slow to access with remap_pfn_range
and that it should instead be faulted in one page at a time.
The commit 5774e219651da3b9bacf9eafd87ae39d75a5eea7 implemented the former
behaviour and caused a performance regression in the VM->VM case.
This commit retores the old behaviour, but extends it to support mmaping
the kvmfr device directly, without going through a dmabuf.
=> [module] fault in pages one by one for ivshmem devices

client/displayservers/SDL/sdl.c, client/displayservers/Wayland/CMakeLists.txt, client/displayservers/Wayland/gl.c, client/displayservers/Wayland/output.c, client/displayservers/Wayland/registry.c, client/displayservers/Wayland/wayland.c, client/displayservers/Wayland/wayland.h, client/displayservers/Wayland/window.c, client/displayservers/X11/x11.c, client/include/app.h, client/include/interface/renderer.h, client/renderers/EGL/alert.c, client/renderers/EGL/alert.h, client/renderers/EGL/egl.c, client/renderers/EGL/fps.c, client/renderers/EGL/fps.h, client/renderers/EGL/help.c, client/renderers/EGL/help.h, client/renderers/OpenGL/opengl.c, client/src/app.c, client/src/main.c, client/src/main.h
This PR adds the support for high DPI with UI scaling.
Currently, only the Wayland display server passes a UI scale factor. All other display servers pass 1 for scale. Both the EGL and OpenGL renderers can render the UI at high resolution, but only the EGL backend scales the alerts, FPS meter, and help overlay by rendering it at high DPI.
Limitations: the desktop does not look very good when upscaled with `LG_SCALE_NEAREST` (currently hardcoded). We might want to add a setting to switch between the different filters.
=> Add high DPI support for Wayland

client/renderers/EGL/texture.c
Reusing cached EGLImages while the frame format has changed will result
in visual artifacts. We should instead destroy the EGLImages and let
them be recreated.
=> [client] egl: destroy cached EGLImages when changing format

client/CMakeLists.txt
We need SSE intrinsics like _mm_stream_load_si128 which is only available
on CPUs of nehalem or newer.
=> [client] cmake: build for nehalem when OPTIMIZE_FOR_NATIVE=NO

.github/workflows/build.yml
Catch possible errors early in CI with release and debug builds.
=> Add release type to CI matrix

client/displayservers/Wayland/output.c, client/displayservers/Wayland/wayland.c, client/displayservers/Wayland/wayland.h, client/displayservers/Wayland/window.c
If the scale factor of an wl_output changes while the client is running,
the maximum scale factor is not updated. This may result in incorrect
scaling.
Therefore, when the scale factor is changed, we should generate a
resize event.
=> [client] wayland: handle output scale changes

client/src/main.c
We moved it to %ProgramData%\Looking Glass (host), but the client still
says it's in %TEMP%.
=> [client] display correct log path on Windows

client/fonts/CMakeLists.txt, client/fonts/freetype/CMakeLists.txt, client/fonts/freetype/src/freetype.c
This backend renders text just like the SDL backend, and has UTF-8 support.
=> [client] fonts: add freetype font rendering backend

client/displayservers/Wayland/clipboard.c, client/displayservers/Wayland/output.c, client/displayservers/Wayland/registry.c, client/displayservers/Wayland/wayland.h, client/displayservers/Wayland/window.c
Before, we just attempt to bind, causing an obscure Wayland error.
This commit checks the interface versions and print better error
messages.
=> [client] wayland: fail gracefully when interfaces are too old

client/displayservers/Wayland/wayland.c
This was missed when splitting up wayland.c into multiple modules.
This commit also drops the useless #include <SDL2/SDL.h>, bringing
SDL removal one step closer.
=> [client] wayland: clean up #includes in wayland.c

client/src/app.c, client/src/main.h
When users press escapeKey for a long time, they probably want to
see the help text instead of actually toggling capture. Therefore,
if the key is held down for more than 500 ms, we assume the user
wants to look at the help text and do not toggle capture mode.
500 ms seems to be a decent compromise, allowing slow presses, but
is not enough time for the user to have looked at the help text.
=> [client] app: do not toggle capture if escapeKey is held

client/CMakeLists.txt, client/README.md, client/displayservers/CMakeLists.txt, client/displayservers/SDL/CMakeLists.txt
This PR also moves the SDL dependencies into the SDL backend so that `-DENABLE_SDL=NO` builds do not link against SDL.
Mentions of SDL are deleted from `README.md` as it's deprecated, defaults to off, and not encouraged. As such, `-DENABLE_SDL=ON` is not mentioned in the README, but we can still tell people to use it if needed.
=> [client] ds: make SDL display server optional

client/README.md
We have an implementation of Wayland cursor warping now, so there is no
need for the section saying that Wayland lacks the feature.
=> [client] readme: remove mention of Wayland's lack of warp

common/src/platform/linux/crash.c
Calling abort() instead of exit() will generate a core dump, allowing gdb
to be used when the client crashes. This is desirable for the following
reasons:
1. gdb can be used to inspect the call stack with far more detail than the
our quick stack trace code, and also allows the access to the heap.
2. Our SIGSEGV handler is unable to use debug symbols for shared libraries,
making it impossible to debug bugs involving drivers and similar.
=> [common] crash/linux: generate core dump when handling SIGSEGV

client/displayservers/Wayland/output.c, client/displayservers/Wayland/wayland.h
We don't necessarily need `wl_output.release`, which is the only
addition in v3.
This allows Looking Glass to run on Ubuntu 20.04 without having to go
difficult lengths to acquire newer Wayland packages. Since 20.04 is an
LTS release, this seems worthwhile for the small amount of complexity
this introduces.
Fixes
https://forum.level1techs.com/t/latest-build-allow-inhibiting-shortcuts-dialog-ubuntu/168684/6.
=> [client] wayland: gracefully downgrade to wl_output v2 

client/displayservers/Wayland/registry.c, client/displayservers/Wayland/window.c
The only addition to v4 was `wl_surface_damage_buffer`, which we do not
use.
This change should allow running on more compositors (even though v4 is
already old -- 5 years now).
Ref
https://gitlab.freedesktop.org/wayland/wayland/-/commit/3384f69ecf043d62a4e036c0353c2daa01d7c4d0.
=> [client] wayland: require wl_compositor v3 instead of v4

client/displayservers/Wayland/clipboard.c
Otherwise, libwayland aborts when a drag into the Looking Glass window
occurs.
=> [client] wayland: bind no-op drag-and-drop handlers

.github/workflows/build.yml
SDL was made optional, and defaulted to off, in c34fe10. However, we
should still make sure it continues building.
=> [client] ds: build SDL backend in CI

host/src/app.c
This is needed for proper cleanup.
Freeing the capture interface also avoids a crash when using the NvFBC
backend. This is because we moved the mouse hook removal to nvfbc_free.
If nvfbc_free is not called before we start freeing LGMP memory, the
mouse hook would end up writing the cursor position into an invalid
memory address, causing an access violation.
=> [host] free capture interface on exit

host/include/interface/capture.h, host/platform/Linux/capture/XCB/src/xcb.c, host/platform/Windows/capture/DXGI/src/dxgi.c, host/platform/Windows/capture/NVFBC/src/nvfbc.c, host/src/app.c
This commit introduces a new option, app:capture, which can be set to
either DXGI or NvFBC to force the host application to use that backend.
This is very useful for testing DXGI on Quadro cards, which would default
to running with NvFBC.
=> [host] allow user to select capture backend

common/include/common/debug.h
Essentially, debug.h defines printTrace as an empty macro when the macro
ENABLE_BACKTRACE is not defined, breaking the compilation of crash.c.
Fixed by defining a private macro for debug.h only to avoid clashing.
=> [common] crash: fix Linux compilation with -DENABLE_BACKTRACE=NO

client/CMakeLists.txt, common/CMakeLists.txt, common/cmake/FindBFD.cmake, common/src/platform/linux/CMakeLists.txt
When linking against libbfd.so, just passing libbfd.so to the compiler is
sufficient. When linking against the static version libbfd.a, however,
we must additionally link against libiberty.a and libz.a.
This commit adds a CMake helper to find the correct libraries that need
to be passed to link against libbfd correctly.
=> [client] cmake: correctly link static libbfd.a

client/displayservers/Wayland/clipboard.c, client/displayservers/Wayland/poll.c, client/displayservers/Wayland/wayland.h
Some of the functions were named WaylandEpoll*, which is inconsistent.
This commit changed them to be WaylandPoll*.
=> [client] wayland: use consistent naming in poll module

client/CMakeLists.txt, client/displayservers/Wayland/CMakeLists.txt, client/displayservers/Wayland/gl.c, client/displayservers/Wayland/input.c, client/displayservers/Wayland/registry.c, client/displayservers/Wayland/shell_libdecor.c, client/displayservers/Wayland/shell_xdg.c, client/displayservers/Wayland/wayland.c, client/displayservers/Wayland/wayland.h, client/displayservers/Wayland/window.c
This PR adds support for using `libdecor` to implement client-side decorations, allowing window decorations (i.e. title bar) to be shown on GNOME Wayland. This only exists to work around the GNOME people's blind belief that server-side decorations don't exist, despite there being a standard protocol for it.
This feature is experimental and can be enabled with `-DENABLE_LIBDECOR=ON`. It is off by default due to extra dependencies (`libdecor`, `cairo`) and the fact that the code is much less tested. Various `libdecor` plugins installed on the system may also cause crashes. Only users running GNOME Wayland and wishes to see decorations should use this feature.
=> Add libdecor pseudo-shell for GNOME Wayland

.github/workflows/build.yml
A $ sign is needed for GitHub Actions to interpolate the variable.
=> [client] ci: correctly set CMAKE_BUILD_TYPE

host/include/interface/platform.h, host/platform/Windows/src/service.c, host/src/app.c
Certain users of Radeon cards have observed that the host fails to start
at boot, with D3D11CreateDevice failing with HSTATUS 0x887a0004, which
translates to "The specified device interface or feature level is not
supported on this system."
This failure results in a LG_HOST_EXIT_FAILED exit code, which the service
does not attempt to restart. The user has to manually restart the service
for the host application to work.
These users reported that the host application started fine on
B2. This strongly suggests that the fix to enable capturing the login
screen made the host application start too early during the boot process,
and the graphics driver did not have time to initialize fully.
This PR allows the service to retry a few times on LG_HOST_EXIT_FAILED,
with exponential backoff, before …
=> [host] service: retry a few times when host fails to restart

host/platform/Windows/src/platform.c, host/platform/Windows/src/platform.h, host/platform/Windows/src/service.c
Instead of doing ShellExecute from the service, we instead get the token
of the currently logged in user, and do CreateProcessAsUserA to run
notepad with that token. This should be safe.
=> [host] windows: re-implement open log safely

client/displayservers/X11/x11.c, client/displayservers/X11/x11.h
... instead of the first two valuators present in the event.  The Xorg
evdev driver can send events with only one valuator set if the mouse only
moved along one axis.
=> Find and use correct valuators for mouse axes

client/displayservers/Wayland/shell_libdecor.c
This commit fixes the -Wmissing-field-initializers warning, which can only
be disabled with a pragma. GCC wants us to Initialize libdecor reserved
fields, which requires knowing how many reserved fields there are.
This is an implementation detail, and so we can only disable the warning.
This also fixes -Wincompatible-pointer-types, which is an actual bug.
=> [client] libdecor: fix gcc compile warnings-turned-errors

client/displayservers/Wayland/cursor.c, client/displayservers/Wayland/wayland.c, client/displayservers/Wayland/wayland.h
This PR frees the `wl_buffer` and `wl_surface` associated with the cursor so that the ASan output is cleaner.
=> [client] wayland: do not leak cursor wl_buffer and wl_surface

client/renderers/EGL/texture.c
Without `glDeleteSync`, memory usage of client slowly increases over time on DMA mode.
=> Do not leak fence on DMA mode

host/platform/Windows/src/service.c
We don't actually have any handles that should be inherited, so specifying
TRUE for bInheritHandles to CreateProcessAsUserA is pointless.
Furthermore, according to MSDN, "[y]ou cannot inherit handles across
sessions," and we are spawning the host in a different session, so this
is even more pointless.
=> [host] service: disable handle inheritance when spawning host

host/platform/Windows/capture/NVFBC/src/nvfbc.c
Since we now let the mouse hook linger until the process is killed, the
cursor event that the hook signals may now be null, as the capture could
have stopped. If the hook fires during this time, a crash occurs.
=> [host] nvfbc: fix null dereference in mouse hook handler

client/README.md, client/src/config.c, client/src/core.c, client/src/main.h
Add command line option to constrain the client's window dimensions to the guest's resolution when `dontUpscale` is also enabled.
I really like `dontUpscale`, but it is annoying that resizing the window above the guest's resolution makes black bars show up around the image.
When this option is enabled, the window is limited to the guest's resolution so you never get the black bars.
=> Add command line option to constrain the client's window dimensions

client/src/app.c, client/src/config.c, client/src/main.h
This option controls the time period (in ms) after which the help menu
appears when holding down the escape key. After this time period,
capture mode is no longer toggled.
This fixes #527.
=> [client] ui: add input:helpMenuDelay option

client/displayservers/Wayland/cursor.c, client/displayservers/Wayland/input.c, client/displayservers/Wayland/wayland.h
This mirrors the x11 implementation, allowing the pointer to move
correctly into overlapping windows.
=> [client] wayland: synchronize host cursor position with guest

client/displayservers/Wayland/input.c, client/displayservers/Wayland/wayland.h, client/displayservers/X11/x11.c, client/include/interface/displayserver.h, client/src/core.c
Using util_cursorToInt messes with the error tracking for normal movements,
and is not necessary since we are computing an absolute position on the
client window.
=> [client] ds: avoid util_cursorToInt when warping pointer

common/include/common/option.h, common/src/option.c
Intersections of table lines have '+' added, and adds new command line flag --rst-help, which adds some extra formatting to the make it an rST compliant table for the in-line docs.
[![image](https://user-images.githubusercontent.com/5211576/117191054-21ec9680-adae-11eb-86f1-789331f4e7bf.png)](https://gist.github.com/JJRcop/045ea8ded8dabe1157558f29643e01d3)
[![image](https://user-images.githubusercontent.com/5211576/117191527-accd9100-adae-11eb-913a-3d46a84c87fa.png)](https://gist.github.com/JJRcop/d7a1598b8b08bd577c5824bd914c0970)
=> [common] option: Reformat help and support rST tables

client/displayservers/SDL/sdl.c, client/displayservers/Wayland/gl.c, client/displayservers/X11/x11.c, client/include/util.h, client/renderers/EGL/egl.c, client/src/util.c, common/include/common/stringutils.h, common/src/stringutils.c
We previously used strstr, which can be prone to false positives when
the name of one extension is a substring of another extension.
This commit creates the helper function util_hasGLExt, which asserts
that the substring found in extension list is bounded by either spaces
or the beginning/end of the string.
=> [client] egl: use new util_hasGLExt helper to check extensions

client/displayservers/SDL/sdl.c, client/displayservers/Wayland/gl.c, client/displayservers/Wayland/registry.c, client/displayservers/Wayland/wayland.h, client/displayservers/Wayland/window.c, client/displayservers/X11/x11.c, client/include/app.h, client/include/egl_dynprocs.h, client/include/interface/displayserver.h, client/renderers/EGL/cursor.c, client/renderers/EGL/cursor.h, client/renderers/EGL/egl.c, client/src/app.c, client/src/egl_dynprocs.c
Instead of damaging the entire surface when rendering a cursor move,
we can use the EGL_KHR_swap_buffers_with_damage extension to only
damage the part of the window covered by the cursor. This should
reduce the cursor movement latency on Wayland.
This should probably be tested by some Wayland users first before merging.
=> [client] egl: use eglSwapBuffersWithDamageKHR for cursor-only updates

client/displayservers/Wayland/gl.c
I somehow forgot to add the file when amending #537. Sorry about the extra commit.
=> [client] wayland: use util_hasGLExt for swapping buffers with damage

client/displayservers/Wayland/input.c
When using locked pointer (i.e. capture mode), it doesn't make sense to
warp the cursor, so we disable it. This fixes #540.
=> [client] wayland: avoid protocol error when warping in capture mode

obs/lg.c
Allocate enough memory for the cursor data!
I think the alpha mask is still messed up for monochrome cursors but at least it doesn't segfault now.
=> [obs] fix oob cursor writes

client/displayservers/Wayland/clipboard.c
Support for non-PNG types is optional in the spice agent, so we should
avoid sending those if PNG is available.
Currently, the spice VDAgent supports only PNG and BMP formats.
=> [client] wayland: prefer PNG over other image types

obs/CMakeLists.txt
`/usr/share/obs/blahblah` is where obs expects to find the dylib, so put it there!
=> [obs] install into plugin dir

client/displayservers/Wayland/clipboard.c
Since we are using epoll, there is no longer any need to remove O_NONBLOCK
with fcntl, and the comment is also no longer relevant.
=> [client] wayland: remove sync transfer for VM->host copies

client/displayservers/Wayland/clipboard.c, client/displayservers/Wayland/input.c, client/displayservers/Wayland/wayland.h
This commit restructures the Wayland clipboard handling for host->VM.
Before, we select one clipboard format and buffers the data for it, to
be presented to spice when needed.
Now, we simply offer all clipboard formats supported, and only when spice
asks for the data do we actually read the wl_data_offer. The wl_data_offer
is kept around until a new offer is presented, the offer invalidated, or
when we lose keyboard focus. This is in accordance with the specification
for wl_data_device::selection, which states that:
> The data_offer is valid until a new data_offer or NULL is received or
> until the client loses keyboard focus. The client must destroy the
> previous selection data_offer, if any, upon receiving this event.
We still buffer the entire clipboard data into memory because we …
=> [client] wayland: offer all supported clipboard formats

common/CMakeLists.txt, common/include/common/runningavg.h, common/src/runningavg.c, host/platform/Windows/capture/DXGI/src/dxgi.c
This change adds an average function to time how long it takes the GPU
to copy and map the texture, and then uses this average to sleep for 80%
of this average lowering CPU usage and potentially decreasing lock
contention.
=> [host] dxgi: sleep until it's close to time to map

client/displayservers/Wayland/input.c, client/displayservers/Wayland/wayland.h
This should fix the occasional Wayland protocol errors that arise when
the UI thread and the cursor thread race.
Example of error that is fixed:
zwp_pointer_constraints_v1@11: error 1: a pointer constraint with a wl_pointer of the same wl_seat is already on this surface
=> [client] wayland: lock confine-related code to avoid race

client/displayservers/Wayland/input.c
This was fixed in 9db3cd7b and accidentally broke again in 4b99bba2.
=> [client] wayland: fix full screen toggle in capture mode regression

client/displayservers/Wayland/clipboard.c
When both text/plain and text/html are available, we should prefer the plain
text as we can't paste HTML.
=> [client] wayland/clipboard: prefer text/plain over text/html

common/src/runningavg.c
We receive values as int64_t, but when we compute the sum, we store it as
int. This doesn't make sense as we eventually cast it to double when
computing the average. We should instead store the sum as int64_t.
=> [common] runningavg: avoid integer overflows

client/CMakeLists.txt, host/CMakeLists.txt
Just a small change that uses `TARGETS` install mode and `CMAKE_INSTALL_BINDIR` to put things in the right place.
=> cmake install targets

host/platform/Windows/CMakeLists.txt
This causes cmake to automatically pick up the right program via `CMAKE_RC_COMPILER` from the toolchain config and use the correct RCFLAGS and so on.
=> [host] avoid manual windres command

client/src/core.c
Conversion from the float values srcW/srcH to the int values for the client window dimensions would sometimes round down, causing the client to scale instead of matching the host's resolution.
=> [client] Fix narrowing issues with win:shrinkOnUpscale param

doc/faq.rst, doc/index.rst
The LG Trello is unmaintained, and we have to fund those rare NFTs somehow.
=> [doc] index: Nuke trello and add ethereum address

doc/module.rst
This works in dash (not just bash), so should be portable to most shells.
Will hopefully help users not misinterpret the period as a mistake.
=> [doc] module: dkms example has explicit "."

host/platform/Windows/capture/NVFBC/src/wrapper.cpp
We return a timeout, so that when protected content finishes playing, we
can immediately resume capture.
The fact we crash with an obscure message (`Unknown NVFBCRESULT failure 0xfffffffc`) was reported on Discord a while ago. I am unable to test this because I don't have any HDCP content.
=> [host] nvfbc: do not crash when protected content is playing

client/displayservers/Wayland/input.c
The unwanted ! was introduced in 4b99bba200da004d134f38f5d8c2a74dead6e436.
This basically caused warp to never be used.
=> [client] wayland: fix typo in warp usage

client/CMakeLists.txt
This doesn't fix build issues with clang, but still helps to not need to depend on a shared library when we are building it with the client.
=> [client] cimgui: build as static library

client/renderers/EGL/texture.c
This removes the need for the driver to allocate texture storage and deleting
the previous allocation on every frame update.
=> [client] egl: use glCopyTexSubImage2D to copy when using DMA

client/renderers/EGL/model.c
This eliminates the need to bind the buffers and set up the vertices on
every frame.
Also fixes a bug that caused buffer objects to be leaked.
=> [client] egl: use vertex array objects in model.c

client/include/egl_dynprocs.h, client/renderers/EGL/egl.c, client/src/egl_dynprocs.c
This reports useful information from OpenGL on supported platforms, including errors, performance warnings, and other things.
=> [client] egl: implement error reporting callback

client/include/util.h, client/renderers/EGL/desktop.c, client/renderers/EGL/desktop.h, client/renderers/EGL/egl.c, client/renderers/EGL/texture.c, client/renderers/EGL/texture.h, client/src/util.c
This speeds up the copy significantly when the frame only has small
amount of damage.
=> [client] egl: only copy damaged areas when using dmabuf

client/include/util.h, client/renderers/EGL/desktop.c, client/renderers/EGL/desktop.h, client/renderers/EGL/egl.c, client/renderers/EGL/texture.c, client/renderers/EGL/texture.h, client/src/util.c
This reverts commit a14de25661ce50fcbbd0c8b000f1d97c90beb716.
Frame is sometimes incorrect.
=> [client] egl: revert "only copy damaged areas when using dmabuf"

client/include/egl_dynprocs.h, client/renderers/EGL/CMakeLists.txt, client/renderers/EGL/egl.c, doc/build.rst
If we specifically tell ImGui's OpenGL 3.x backend to target OpenGL ES 3.0,
then no extension loader is necessary.
=> [client] imgui: use ES 3.0 and remove glew dependency

client/include/egl_dynprocs.h, client/renderers/EGL/egl.c, client/renderers/EGL/egldebug.c, client/renderers/EGL/model.h, client/renderers/EGL/shader.h, client/renderers/EGL/splash.c, client/renderers/EGL/texture.c, client/renderers/EGL/texture.h
Instead of using the desktop <GL/gl.h>, we properly use the OpenGL ES 3.x
headers. Also, we now use GL_EXT_buffer_storage for MAP_PERSISTENT_BIT_EXT
and MAP_COHERENT_BIT_EXT as the core versions are only available in desktop
OpenGL 4.4. Similarly, we need GL_EXT_texture_format_BGRA8888 for GL_BGRA_EXT
as GL_BGRA is desktop-only.
=> [client] egl: properly use OpenGL ES

.github/workflows/build.yml
We removed the GLEW dependency, so we shouldn't be installing it.
=> [client] ci: do not install libglew-dev

client/CMakeLists.txt, client/displayservers/Wayland/gl.c, client/displayservers/Wayland/wayland.h, client/displayservers/X11/x11.c, client/include/eglutil.h, client/src/eglutil.c
This commit creates a new utility library, eglutil.h, which contains code
to detect and use EGL_KHR_swap_buffers_with_damage or its EXT equivalent.
This logic used to be duplicated between the X11 and Wayland display servers,
which is not ideal.
**Note**: This has not been tested on X11, but it should work.
=> [client] ds: refactor common EGL swap with damage logic

client/renderers/EGL/egldebug.c, client/renderers/EGL/egldebug.h, client/renderers/EGL/texture.c
We used to use DEBUG_EGL_ERROR for gl* functions, which just yields
EGL_SUCCESS even when there are errors.
=> [client] egl: use glGetError and codes for errors in gl* functions

host/platform/Windows/CMakeLists.txt, host/platform/Windows/src/platform.c, host/platform/Windows/src/service.c
This allows the process to be terminated without resorting to
TerminateProcess. With some fixes, this allows the notification icon to be
removed when the service is restarted.
Furthermore, instead of sending WM_DESTROY to fool the window into believing
it's being destroyed, we actually call DestroyWindow now.
=> [host] windows: use event to gracefully signal exit

host/platform/Windows/src/service.c
According to MSDN documentation for CreateEnvironmentBlock, "[i]f the
environment block is passed to CreateProcessAsUser, you must also
specify the CREATE_UNICODE_ENVIRONMENT flag."
Also pass DETACHED_PROCESS because the host is a GUI application and
doesn't use the console.
=> [host] service: pass CREATE_UNICODE_ENVIRONMENT unconditionally

client/renderers/EGL/cursor.c, client/renderers/EGL/cursor.h, client/renderers/EGL/egl.c
1. Use atomics and return exact cursor positions from egl_cursor_render
to avoid race conditions between cursor render and update.
2. Instead of messing with lastCursorValid in various overlays, simply use
the hasOverlay/hadOverlay logic for cursor damage. This simplifies the
logic greatly.
As a result, I believe all cursor-related artifacts are fixed.
Note to reviewer: as atomic_init and atomic_store are implemented as macros,
it is currently not possible to pass structs as compound literals due to the
comma being interpreted as an argument separator by the preprocessor.
=> [client] egl: improve cursor damage logic

host/platform/Windows/src/service.c
When OpenProcessToken fails, the function returned -1, which would be true
when converted to bool. This is wrong, and it should be returning false.
=> [host] service: fix adjustPriv return value

host/platform/Windows/CMakeLists.txt, host/platform/Windows/include/windows/delay.h, host/platform/Windows/src/delay.c
There is no need to LoadLibrary and GetProcAddress to get pointers to
NtDelayExecution or NtSetTimerResolution. These functions don't have
prototypes in any SDK header, but they are exported in ntdll.dll and
we can simply declare the prototype and link ntdll.
There is also no chance that the functions do not exist: I checked an
old install of Windows NT 4.0 and both of these functions exist.
Also used NtSetTimerResolution instead of ZeSetTimerResolution for
consistency (they are the same).
Also changed system timer resolution log message units to μs with
one decimal digit for readability. This is the actual amount of
precision available to us.
=> [host] delay: directly link against ntdll.dll

host/platform/Windows/CMakeLists.txt
We wanted to target Windows Vista, which is 0x0600 not 0x6000.
0x6000 is in fact larger than Windows 10 which is 0x0a00.
=> [host] windows: correctly declare WINVER and _WIN32_WINNT

host/platform/Windows/app.manifest, host/platform/Windows/src/platform.c
This is the normal way of doing things, and it's easier and less sketchy
than GetProcAddress.
=> [host] windows: declare high DPI support in manifest

common/include/common/windebug.h, common/src/platform/windows/windebug.c, host/platform/Windows/app.manifest, host/platform/Windows/capture/DXGI/src/dxgi.c
Just declare Windows 10 in manifest and use `<versionhelpers.h>` from Windows SDK.
DXGI is changed to use `<versionhelpers.h>`. At the same time, also changed logic so that Windows versions before 8 is not treated as 10, and switched to using `ARRAY_LENGTH` helper.
=> [common] windebug: remove custom-rolled Windows 8 detector

host/platform/Windows/CMakeLists.txt
a4f5ce08b93c101ea797bef058d6f3a6f832a2f4 has a regression that caused
the .rc file to be compiled twice. We do not want the version that's
added into the .a file.
=> [host] windows: avoid compiling .rc file twice

host/CMakeLists.txt
It used to be the case that when updating app.manifest, the resource file
it not automatically rebuilt. This made it a headache to update the manifest.
We set OBJECT_DEPENDS so that cmake knows to make the res file depend on
app.manifest and icon.ico.
This commit is based on PR #579 and should be rebased on it after it's merged.
=> [host] windows: fix resource compilation dependencies

common/src/platform/windows/CMakeLists.txt
This is done for consistency with the Windows-specific portions of the host.
=> [common] windows: declare WINVER and _WIN32_WINNT

client/displayservers/Wayland/presentation.c
We don't need the presentation time protocol, so fail gracefully when
it's unavailable.
=> [client] wayland: do not crash when presentation time is unavailable

host/platform/Windows/src/delay.c
The type of the QuadPart member of the LARGE_INTEGER union is actually
LONGLONG, so we should cast to LONGLONG instead of int.
This avoids truncation should (ms * 10000.0f) exceed 2^31-1.
=> [host] windows/delay: cast to LONGLONG instead of int

host/platform/Windows/src/mousehook.c, host/platform/Windows/src/service.c, host/src/app.c
We were using an auto-reset event to signal the mousehook exit. This was
fine when there was only one thread, but with the addition of the update
thread, only one thread is signaled, causing the wait to last forever.
The fix is switching to a manual reset event and call ResetEvent after
the threads have exited.
=> [host] windows: fix graceful exit

host/CMakeLists.txt, host/platform/Windows/resource.rc, version.cmake
This allows friendly names and versions to be displayed in task manager
and other applications.
=> [host] windows: add version resource

client/renderers/OpenGL/opengl.c
The OpenGL renderer backend should not depend on any particular
implementation of OpenGL, as it's used by both X11 and Wayland.
=> [client] opengl: don't include <GL/glx.h>

host/platform/Windows/src/force_compose.c, host/platform/Windows/src/mousehook.c
This function is sometimes flaky and may fail for no apparent reason,
see https://stackoverflow.com/q/3945003. This has also been experienced
during the development of #610.
This commit adds logging so we may see if it ever fails for no reason
and work out some way to fix it.
=> [host] windows: log MsgWaitForMultipleObjects errors

host/platform/Windows/CMakeLists.txt, host/platform/Windows/ntdll.def
MinGW seems to decide at random whether it wants to use memcpy from
mscvrt.dll or ntdll.dll. Currently, on Debian buster, ntdll.dll is chosen,
while on sid, mscvrt.dll is chosen.
This commit declares a new .def file for ntdll containing only the
functions we want to link from ntdll.dll, and generates ntdll.a from it
with dlltool. This way, MinGW will never be tempted to link functions
like memcpy from ntdll.dll.
=> [host] windows: trick MinGW into not using memcpy from ntdll

.github/workflows/build.yml
Our code to generate object files from shaders with the linker seems to
depend on GNU ld. More accurately, it works with lld, but we must specify
the correct object format via -m, which is very difficult to detect in a
satisfactory manner. Therefore we simply force use of GNU ld.
=> [client] ci: fix clang build

.github/workflows/build.yml
We source libdecor packages from a PPA.
This is dependent on #637.
=> [client] ci: test libdecor build as part of matrix

host/platform/Windows/src/platform.c
DestroyWindow can only be invoked on the thread that created the window.
All other threads must use WM_CLOSE or another message to signal tell the
window to destroy itself.
=> [host] windows: use WM_CLOSE to signal window destruction

client/include/app.h, client/renderers/EGL/egl.c, client/renderers/OpenGL/opengl.c, client/src/app.c
This makes everything consistent.
=> [client] renderers: treat -1 as full damage and 0 as no overlay

.github/workflows/build.yml
This is desirable because certain uncommon configurations like libdecor or
clang may break, and this shouldn't stop us from seeing if unrelated changes
pass.
=> [client] ci: run all build combinations to completion

common/src/platform/windows/time.c, host/platform/Windows/src/platform.c
When our window is destroyed, our timers are also destroyed. This causes our
attempt at destruction to fail. Instead, set MessageHWND to NULL in the
WM_DESTROY handler and don't try destroying the timers if the window is gone.
=> [host] windows: do not complain about failed timer destruction at exit

client/renderers/EGL/egl.c
This allows the full frame to be damaged when both types are visible.
=> [client] egl: correctly handle mixing imgui and non-imgui overlays

client/CMakeLists.txt, client/include/app.h, client/include/overlay_utils.h, client/renderers/EGL/egl.c, client/src/app.c, client/src/overlay/fps.c, client/src/overlay/graphs.c, client/src/overlay_utils.c
This is necessary in case overlays change size. When this happens, we must
damage the larger of the overlays' rectangles this frame and last frame.
This erases the overlay from where it is no longer appears.
In order to do this, we must keep track of the rectangles for every overlay
with no exception. We cannot short-circuit the generation of rectangles if
we run out of buffer space, and we must allocate space for MAX_OVERLAY_RECTS
rectangles for every frame. Otherwise, we will not know where to erase the
overlay if it disappears.
=> [client] imgui: track last rectangles for overlays

client/CMakeLists.txt, client/include/util.h, client/renderers/EGL/egl.c, client/renderers/OpenGL/opengl.c, client/src/app.c, client/src/config.c, client/src/main.c, client/src/main.h, client/src/overlay/graphs.c, client/src/overlay_utils.cpp, client/src/util.c
This implementation makes imgui render at a higher resolution, avoiding scaling resulting blurriness.
This is dependent on #645.
=> [client] imgui: use improved high DPI rendering

host/platform/Windows/CMakeLists.txt
cmake automatically finds dlltool as of version 3.16, but I kept the `find_program` around as a fallback in case of systems with older cmake versions?
=> [host] windows: use CMAKE_DLLTOOL

client/displayservers/Wayland/shell_libdecor.c, client/displayservers/Wayland/shell_xdg.c
This avoids sending potentially meaningless damage values after a surface
configuration event.
=> [client] wayland: invalidate window on configure

client/renderers/EGL/cursor.c
This shifts the rectangles upwards instead of cutting off the rectangles,
but it keeps the code simple.
=> [client] egl: keep x/y coordinates of cursor rectangle non-negative

client/src/main.c
Also removed the inefficient code to build the default atlas.
=> [client] imgui: report failed font atlas building

common/include/common/time.h
We implement nanotime by converting QueryPerformanceTimer output with
floating point arithmetic. This is necessary to preserve precision on
platforms where each tick is not an integer number of nanoseconds.
Furthermore, struct timespec is included C11 and appears to be supported
on Windows, so we no longer need to #ifdef it out.
=> [common] time: fully implement all functionality for windows

common/src/framebuffer.c
We used to increment the source buffer index by width * bpp, not by pitch.
This is incorrect and the root cause behind #670.
This is a regression that appeared in 196050bd2381f4d7dbf6149c3347932951a47ebf.
This PR fixes #670.
=> [common] framebuffer: fix copy when source and dest pitch differs

client/displayservers/Wayland/presentation.c, client/include/app.h, client/renderers/EGL/egl.c, client/src/app.c, client/src/main.c, client/src/overlay/graphs.c, client/src/overlays.h
The default of [0, 50] makes sense for FPS/UPS graphs, but does not for
things like the import graph. The latter should not take more than 5 ms
for sure.
This commit allows the min/max y-axis value to be specified when registering
the graph.
=> [client] imgui: make graph y-axis configurable

client/src/app.c, client/src/keybind.c, client/src/overlay/help.c
This replaces the alert that says whether the overlay is enabled or not.
Also, we now always display the help menu in overlay mode.
=> [client] imgui: darken background when rendering overlays

client/src/app.c, client/src/keybind.c
1. Overlay always releases confines.
2. Overlay turns off mouse sync with guest.
=> [client] imgui: improved overlay input handling

client/displayservers/Wayland/CMakeLists.txt, client/displayservers/Wayland/cursor.c, client/displayservers/Wayland/input.c, client/displayservers/Wayland/wayland.c, client/displayservers/Wayland/wayland.h, client/displayservers/X11/x11.c, client/include/interface/displayserver.h, client/src/app.c, client/src/core.c, client/src/keybind.c, client/src/main.c, client/src/main.h
The display server gains an enumeration of supported cursors:
* On Wayland, we use `wayland-cursor` which comes with `libwayland` to load cursors. This is implemented.
* On X11, we likely need to use `Xcursor` to load cursors.
=> [client] ds/imgui: use display server to display various imgui cursors

client/src/config.c, refresh-copyright
The refresh-copyright script now automatically updates the copyright string
embedded in config.c. In order to achieve this, refresh-copyright gained the
ability to reflow text as the situation needs.
=> [client] config: automatically update embedded copyright string

client/src/kb.c, client/src/kb.h, client/src/main.c
This allows ImGui to understand some of the basic key presses.
Also moved the include guard from kb.c to kb.h where it actually makes sense.
=> [client] imgui: initialize keymap

client/displayservers/Wayland/input.c
Currently, we handle horizontal scroll events as if they are vertical scrolls.
This is not correct and we should instead reject them.
=> [client] wayland: reject horizontal scroll events

client/displayservers/Wayland/input.c, client/include/app.h, client/src/app.c
The display server should call `app_handleWheelMotion` as necessary. This is done for Wayland, but not X11.
=> [client] imgui: implement mouse wheel motion support

client/src/main.c
We don't want to encourage craziness of people making the client suid to
bypass permission issues on the shm file.
Note: I see no evidence of this happening in the wild, but let's be
proactive.
=> [client] main: prevent the user from launching looking glass as setuid

client/src/config.c
This makes it clear to the user that app:configFile is at fault.
This is inspired by an incident on Discord today that took a while to figure out.
=> [client] config: print error when app:configFile is not a valid file

common/src/option.c
It is not obvious that [DXGI] and [dxgi] are different sections in the ini file,
and only the latter works. We should just eliminate the difference.
=> [common] option: make options case insensitive

host/platform/Windows/capture/NVFBC/src/wrapper.cpp
This makes troubleshooting easier.
We also switch to use %d instead of 0x%x because all error codes in nvfbc.h
are negative decimal numbers.
=> [host] nvfbc: log error codes for various errors

client/src/app.c
This prevents the escape key from being treated as held down indefinitely when
losing focus while holding the escape key.
=> [client] client: release escape key on focus loss

client/src/config.c
Currently, we load /etc/looking-glass-client.ini and/or
~/.config/looking-glass-client.ini as long as they exist, even if they are
not files. We should only load them if they are files.
=> [client] config: do not attempt to load non-files as config

client/displayservers/Wayland/wayland.c, client/displayservers/Wayland/wayland.h, client/displayservers/Wayland/window.c, client/include/interface/displayserver.h, client/src/main.c, client/src/main.h
This PR adds the optional display server method `signalNextFrame(LGEvent)`, which takes an LGEvent and signals it when the next frame should be rendered in time for the next vblank. This is currently implemented only for Wayland, and must be invoked before swapping buffers.
This is currently used to render imgui at screen refresh rate.
In theory, this could potentially be used later to implement a better form of vsync for supported display servers. Currently, vsync blocks inside swap until the next vblank, upon which the frame is displayed. This is undesirable as we perform the render early and then waits for the vblank. With `signalNextFrame`, we could render the next frame just in time for vblank.
=> [client] ds/imgui: render at screen refresh rate on Wayland

client/src/config.c, client/src/main.c, common/include/common/paths.h, common/src/platform/linux/CMakeLists.txt, common/src/platform/linux/paths.c
This abstracts away stuff like XDG base directory specification.
Currently, this is implemented for Linux only.
Also, the client now loads its config file based on new the `lgConfigDir()` function.
=> [common] paths: add library to manage platform-specific paths

doc/install.rst
A change to the overlay mode keybinding that happened after the original PR that I missed.
=> [doc] install: Update overlay mode keybinding

client/src/config.c, client/src/main.c, client/src/main.h
When requested, JIT render mode will be used if the display server supports it.
Otherwise, a warning is generated instead.
This essentially uses the signalNextFrame logic for imgui, but for everything.
We automatically enable this mode when overlay is on.
Currently, this exposes some damage tracking bugs in the EGL renderer.
=> [client] main: implement just-in-time render mode

client/displayservers/Wayland/CMakeLists.txt, client/displayservers/Wayland/gl.c, client/displayservers/Wayland/output.c, client/displayservers/Wayland/registry.c, client/displayservers/Wayland/wayland.c, client/displayservers/Wayland/wayland.h, client/displayservers/Wayland/window.c
Currently, we scale the desktop up to the next largest integer, and rely on
the wayland compositor to scale it back down to the correct size.
This is obviously undesirable.
In this commit, we attempt to detect the actual fractional scaling by finding
the current active mode in wl_output, and dividing it by the logical screen
size reported by xdg_output, taking into consideration screen rotation.
We then use wp_viewporter to set the exact buffer and viewport sizes if
fractional scaling is needed.
Since the method used is not guaranteed to work on all Wayland compositors, we add an option to make this opt-out. We need to support it anyways in case xdg_output or wp_viewporter protocols are not available.
=> [client] wayland: improve fractional scale handling

client/renderers/EGL/egl.c
If we invalidate the window, we used to not update this->cursorLast, and
this causes us to lose track of the cursor. Now we update this->cursorLast
unconditionally, and this fixes the issue.
=> [client] egl: fix cursor handling when invalidating

client/src/config.c
Without configuring Wayland compositors to send frame callbacks as late as
possible, JIT rendering can increase latency by more than one frame.
For example, by default, sway asks applications to render right after a
vblank, and does its own composition right after a vblank, resulting in
~2 frame's worth of latency. If max_render_time is set on the output,
it composes that many milliseconds before the vblank, losing ~1 frame's
worth of latency. If max_render_time is set on the window also, the frame
callback is sent that many milliseconds before composition, and we achieve
perfectly low latency.
Therefore, out of the box, JIT rendering should not be enabled, as manual
compositor configuration is required for optimal results.
For reference, the following sway settings results in the best …
=> [client] config: disable JIT rendering by default

client/displayservers/Wayland/shell_libdecor.c, client/displayservers/Wayland/shell_xdg.c, client/displayservers/Wayland/wayland.c, client/displayservers/Wayland/wayland.h, client/displayservers/Wayland/window.c, client/include/interface/displayserver.h, client/src/main.c
Add `skipFrame` to display server interface. If this exists, it should be called when `waitFrame` returns but we don't wish to render. This is used to allow Wayland `waitFrame` to work when called without rendering in between.
We also need to signal `frameEvent` to render the first frame. Otherwise, Wayland fails to configure the window, as configuration happens in EGL swap.
=> [client] wayland: make waitFrame work when not rendering

client/displayservers/Wayland/shell_libdecor.c, client/displayservers/Wayland/shell_xdg.c, client/displayservers/Wayland/wayland.c, client/displayservers/Wayland/wayland.h, client/displayservers/Wayland/window.c, client/include/interface/displayserver.h, client/src/main.c
This is used on exit to unblock the render thread.
This is implemented for Wayland.
=> [client] ds: add stopWaitFrame to terminate waitFrame early

client/displayservers/Wayland/gl.c, client/displayservers/Wayland/window.c
This makes it not require new frames for new scale to be properly applied.
=> [commit] wayland: invalidate window on scale changes

client/renderers/EGL/damage.c, client/renderers/EGL/egl.c
After the damage queue PR, EGL damage count 0 means no change, and -1 means
invalidate the entire window. However, several other places have different
semantics, and we are not handling them correctly:
1. KVMFR uses 0 to signal invalidating the entire frame, so if we receive 0
rectangles in egl_on_frame, we should set damage count to -1.
2. The damage overlay treated 0 as full damage, which is now incorrect. This
is fixed, and now it treats 0 as no update, and -1 as full damage.
=> [client] egl: use new EGL damage count semantics

host/platform/Windows/capture/NVFBC/src/nvfbc.c
Fixes log spam that would occur when using `decoupleCursor=false` integrated capture mode, generating hundreds of MBs in seconds!
=> [host] nvfbc: disable pointerThread when unused

client/displayservers/Wayland/gl.c
Add a comment so we don't forget and remove the "useless" code.
=> [client] wayland: document wlroots viewport handling workaround

client/include/util.h, client/renderers/EGL/CMakeLists.txt, client/renderers/EGL/damage.c, client/renderers/EGL/desktop.c, client/renderers/EGL/desktop.h, client/renderers/EGL/desktop_rects.c, client/renderers/EGL/desktop_rects.h, client/renderers/EGL/egl.c, client/renderers/EGL/shader/desktop.vert, client/renderers/EGL/shader/desktop_rgb.frag, client/renderers/EGL/texture_dmabuf.c, client/src/util.c
We avoid rendering any area that has not changed since the buffer was used and also not covered by an overlay.
In order to do this, we refactored the damage mesh generation into a new module, `desktop_rects.c`, which is then used by the desktop module to render its mesh.
As part of this, we simplified and refactored all coordinate space conversions, changing them to use matrices. We are also able to remove the texture copy in the dmabuf path.
=> [client] egl: use buffer age extension to render only damaged parts

client/src/app.c
This allows it to take into the overlays into consideration when deciding
which cursor is to be shown.
=> [client] imgui: move cursor change to after rendering overlays

host/platform/Windows/capture/NVFBC/src/nvfbc.c, host/platform/Windows/capture/NVFBC/src/wrapper.cpp, host/platform/Windows/capture/NVFBC/src/wrapper.h
This commit adds a new host configuration option, nvfbc:diffRes, which
specifies the dimensions of every block in the diff map. This defaults to
128, meaning the default 128x128 block size.
Since block sizes other than 128x128 is not guaranteed to be supported by
NvFBC, the function NvFBCGetDiffMapBlockSize was introduced to query the
support and output the actual block size used.
Not sure if smaller block sizes actually make sense, however. Will need benchmarks to find out.
=> [host] nvfbc: make diff map size configurable

client/renderers/EGL/egl.c
We want to add extra padding to deal with scaling, which may end up blending
with neighbouring pixels.
=> [client] egl: pad buffer damage by 1px when rendering desktop

client/src/overlay/config.c
It looks really weird having a separator right after a sentence ending in :.
A separator makes the list look detached from the paragraph that introduces
it, which looks awkward. Instead, this commit moves the separator before the
introducing paragraph.
Also added logic to properly pluralize the sentence.
=> [client] overlay: move separator above donation prompt

client/renderers/EGL/desktop.c, client/renderers/EGL/desktop.h, client/renderers/EGL/egl.c, client/renderers/EGL/texture.c, client/renderers/EGL/texture.h, client/renderers/EGL/texture_buffer.h, client/renderers/EGL/texture_framebuffer.c, common/CMakeLists.txt, common/include/common/framebuffer.h, common/include/common/rects.h, common/src/framebuffer.c, common/src/rects.c, host/platform/Windows/capture/DXGI/src/dxgi.c, host/platform/Windows/capture/NVFBC/src/nvfbc.c
This uses the same line sweep algorithm originally created to copy DXGI textures to IVSHMEM to implement the copy from IVSHMEM to memory-mapped pixel buffer objects.
=> [client] egl: implement partial copies for framebuffer textures

client/renderers/EGL/texture_buffer.c, client/renderers/EGL/texture_buffer.h
It used to be the case that we overwrite this->sync even if it was non-zero
when updating the texture, without deleting the sync object. If we update
faster than we render, the result would be leaking sync objects.
This commit ensures that sync objects are deleted when they are replaced.
=> [client] egl: eliminate GLsync object leaks

client/renderers/EGL/desktop.c, client/renderers/EGL/egl.c
This should deal with drivers not supporting our DMABUF without attempting
to identify the drivers and blacklist them.
Note: this has not been tested on the `nvidia` driver, failure mode was tested by simulating `return false` in `egl_texture_update_from_dma`.
=> [client] egl: attempt DMABUF import and fallback if it fails

client/renderers/EGL/shader/desktop.vert
In GLSL, using the / operator on two vectors of the same size divides the
vector component-wise, i.e. vec2(a, b) / vec2(c, d) == vec2(a / c, b / d).
=> [client] egl: simplify desktop vertex shader

client/renderers/EGL/shader/basic.vert, client/renderers/EGL/texture.c
`gl_Position` is expected to be using homogeneous coordinates, which requires
w to be a coordinate scale factor, usually 1.0. z should also be set in order
for depth to be well-defined. Therefore, we should set `gl_Position.zw` to
`vec2(0.0, 1.0)`.
Also fixed a flexible array member usage. Note that array size of 0 is a gcc extension, the standard C is not declaring a size.
=> [client] egl: correct assign to gl_Position in basic.vert

client/renderers/EGL/texture_framebuffer.c
This prevents the code from using damage rectangles that are no longer on the
screen, causing an out-of-bounds write.
=> [client] egl: perform full copy for framebuffer textures after resize

client/cmake/MakeObject.cmake
This prevents issues like obscure characters getting transformed in symbol
names, resulting in an endless game of whack-a-mole finding symbols that are
replaced, such as 58964ce3175a0ca92b4c7e66aedb374d71b8af68.
=> [client] cmake: make MakeObject use relative paths

client/renderers/EGL/filter_ffx_fsr1.c
This also displays a tooltip to explain that quality can be changed by altering guest resolution and also show the resolutions needed to achieve each quality mode.
Also fixed a bug that caused the filter state to not change upon resolution change.
=> [client] egl: display FSR equivalent quality mode

client/renderers/EGL/shader/color_blind.h, client/renderers/EGL/shader/cursor.vert, client/renderers/EGL/shader/cursor_mono.frag, client/renderers/EGL/shader/cursor_rgb.frag, client/renderers/EGL/shader/damage.frag, client/renderers/EGL/shader/desktop.vert, client/renderers/EGL/shader/desktop_rgb.frag, client/renderers/EGL/shader/splash_bg.frag, client/renderers/EGL/shader/splash_bg.vert, client/renderers/EGL/shader/splash_logo.frag
We simply use precision mediump float; for everything. We don't actually
need highp anyways, and we don't use it for stuff like CAS or FSR.
=> [client] egl: remove needless precision quantifiers

client/renderers/EGL/desktop_rects.c
The module has been changed to support variable amount of rectangles,
so we should just allocate a VLA.
=> [client] egl: fix buffer overflow in desktop_rects module

client/renderers/EGL/filter_downscale.c
When using DMABUF, the mipmaps can cause driver hangs and crashes.
=> [client] egl: don't generate mipmaps in downscale filter

common/include/common/rects.h, common/src/rects.c, host/platform/Windows/capture/NVFBC/src/nvfbc.c
This makes nvfbc report less useless damage and makes the client run faster.
=> [host] nvfbc: remove rectangles that are entirely contained in others

host/CMakeLists.txt
This commit makes the crash handler show relative paths instead of absolute
ones, which makes the stack traces generated easier to read.
On the other hand, absolute paths makes sense on Linux, since the user is
expected to build the binaries themselves, and gdb will be able to find the
source code.
Example simulated stack trace before:
```
[E]   1549537856             crash.c:132  | exception_filter               | [trace]:  1: C:\Program Files\Looking Glass (host)\looking-glass-host.exe:nvfbc_deinit+0x12 (\home\quantum\build\LookingGlass\host\platform\Windows\capture\NVFBC\src\nvfbc.c:293+0x0)
[E]   1549538725             crash.c:132  | exception_filter               | [trace]:  2: C:\Program Files\Looking Glass (host)\looking-glass-host.exe:captureStop+0xcf …
```
=> [host] windows/crash: do not report absolute paths on build machines

common/src/platform/linux/ivshmem.c
Before, if the size is exactly the multiple of the page size, an extra padding
page is added for no reason. This commit fixes the logic and also uses the
page size obtained dynamically.
=> [common] ivshmem: use correct page alignment logic

common/include/common/array.h, common/src/platform/linux/ivshmem.c, host/platform/Windows/capture/NVFBC/src/nvfbc.c
`ALIGN_PAD(x, a)` returns `x` rounded up to the nearest multiple of `a`.
=> [common] array: add ALIGN_PAD macro for common logic

client/displayservers/Wayland/clipboard.c, client/include/interface/displayserver.h, client/include/interface/overlay.h, client/renderers/EGL/cursor.c, client/renderers/EGL/desktop_rects.c, client/renderers/EGL/egl.c, client/renderers/EGL/model.c, client/renderers/EGL/texture.c, client/renderers/EGL/texture_buffer.c, client/renderers/EGL/texture_dmabuf.c, client/renderers/EGL/texture_framebuffer.c, client/src/app.c, client/src/core.c, client/src/ll.c, client/src/main.c, client/src/util.c, common/include/common/debug.h, common/src/option.c, common/src/platform/linux/event.c, common/src/platform/linux/ivshmem.c, common/src/platform/windows/ivshmem.c, host/platform/Linux/capture/XCB/src/xcb.c, host/platform/Windows/capture/DXGI/src/dxgi.c, host/platform/Windows/capture/NVFBC/src/nvfbc.c
`DEBUG_ASSERT`, unlike the standard `assert` macro, is guaranteed to print the failed assertion to our log file, and tests the assertion even with `NDEBUG` defined so we can more easily catch failures in production binaries without crashing the program. Everywhere `assert` is used, we replace it with `DEBUG_ASSERT`.
The motivation of this is how MinGW handles assertion failures: it creates a dialog window that the headless user will not be able to see, and blocks the program from being restarted by the service. Since the failed assertion is displayed in the dialog, it doesn't print anything to the log, making it impossible to diagnose issues.
`DEBUG_UNREACHABLE` macro lets us mark code as unreachable and signals the compiler that this is the case with `__builtin_unreachable()`. We use …
=> [common] debug: add DEBUG_ASSERT and DEBUG_UNREACHABLE macros

client/renderers/EGL/CMakeLists.txt, client/renderers/EGL/filter_downscale.c, client/renderers/EGL/shader/downscale_lanczos2.frag, client/renderers/EGL/shader/downscale_linear.frag
This pull request adds two new downscaling filters: a bilinear filter and a lanczos filter with window = 2. It also adds UI to switch between the filters.
Note that I am not exactly sure if my lanczos implementation is correct.
=> [client] egl: implement linear and lanczos downscale filter

client/displayservers/Wayland/input.c, client/include/app.h, client/src/app.c
This is currently implemented for Wayland, though it shouldn't be hard to implement for X11 after implementing keyboard input support.
=> [client] spice: synchronize keyboard LED state

client/renderers/EGL/filter_ffx_cas.c, client/renderers/EGL/filter_ffx_fsr1.c
With the new keymap feature, we are now able to properly support letting
the user enter exact values into the sliders. This commit adds a tooltip
to help the user discover this feature.
Note that this currently only works on Wayland. The X11 backend will need
to call app_handleKeyboardModifiers.
=> [client] egl: add tooltip about Ctrl+Click on sharpness sliders

obs/lg.c
This allows users to be aware that the option exists and they should upgrade.
=> [obs] display DMABUF option but disable it on older OBS

client/displayservers/Wayland/clipboard.c, client/displayservers/Wayland/poll.c, client/displayservers/Wayland/presentation.c, client/displayservers/Wayland/window.c, client/displayservers/X11/clipboard.c, client/renderers/EGL/cursor.c, client/renderers/EGL/damage.c, client/renderers/EGL/desktop_rects.c, client/renderers/EGL/draw.c, client/renderers/EGL/model.c, client/renderers/EGL/splash.c, client/src/app.c, client/src/ll.c, client/src/overlay/graphs.c, common/src/countedbuffer.c, common/src/option.c, common/src/platform/linux/crash.c, common/src/platform/linux/event.c, common/src/platform/linux/ivshmem.c, common/src/platform/linux/thread.c, common/src/platform/linux/time.c, common/src/platform/windows/ivshmem.c, common/src/platform/windows/thread.c, common/src/platform/windows/time.c, common/src/stringlist.c, host/platform/Linux/capture/XCB/src/xcb.c, host/platform/Windows/capture/DXGI/src/dxgi.c, host/platform/Windows/capture/NVFBC/src/nvfbc.c, host/platform/Windows/capture/NVFBC/src/wrapper.cpp
This eliminates the class of bugs where the size of the variable being assigned doesn't match the amount of memory being allocated.
=> Use variable-relative sizeof where possible

client/renderers/EGL/egl.c
According to the [documentation for `eglQueryString`](https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglQueryString.xhtml):
> `EGL_BAD_DISPLAY` is generated if display is not an EGL display connection, unless display is `EGL_NO_DISPLAY` and name is `EGL_EXTENSIONS`.
Therefore, we should check EGL by doing:
```c
eglQueryString(EGL_NO_DISPLAY, EGL_EXTENSIONS)
```
Indeed, the old way of `eglQueryString(EGL_NO_DISPLAY, EGL_VERSION)` works on libglvnd but not using mesa's libEGL.so directly.
Also added a warning to make it more obvious that EGL is not available.
=> [client] egl: use standard-compliant way of EGL detection

client/renderers/EGL/texture_dmabuf.c, client/renderers/EGL/texture_framebuffer.c, common/src/platform/linux/event.c, common/src/platform/windows/ivshmem.c, host/platform/Linux/capture/XCB/src/xcb.c, host/platform/Windows/capture/DXGI/src/dxgi.c, host/platform/Windows/capture/NVFBC/src/nvfbc.c, host/platform/Windows/capture/NVFBC/src/wrapper.cpp
The signature for calloc is `void *calloc(size_t num, size_t size)`, where `num` is the number of elements to allocate, and `size` is the size. Therefore, to allocate a single struct, we should pass `1` for `num` and the size of the struct as `size`.
In some places, we use the opposite order, and we should flip it.
This is based on #778 and should be rebased after it is merged.
=> [all] use correct argument order for calloc

client/renderers/EGL/desktop_rects.c
We pad the screen coordinates and then convert to desktop coordinates,
so that the padding will always be a pixel wide on screen.
=> [client] egl: pad areas of the desktop repainted to cover overlays

client/displayservers/X11/clipboard.c, client/renderers/EGL/cursor.c, client/renderers/EGL/damage.c, client/renderers/EGL/desktop.c, client/renderers/EGL/draw.c, client/renderers/EGL/model.c, client/renderers/EGL/shader.c, client/renderers/EGL/splash.c, client/renderers/EGL/texture_buffer.c, client/renderers/EGL/texture_dmabuf.c, client/renderers/OpenGL/opengl.c, client/src/app.c, common/src/option.c, common/src/platform/linux/crash.c, common/src/platform/linux/event.c, common/src/platform/linux/ivshmem.c, common/src/platform/linux/thread.c, common/src/platform/windows/ivshmem.c, common/src/platform/windows/thread.c, host/platform/Linux/capture/XCB/src/xcb.c, host/platform/Windows/capture/NVFBC/src/nvfbc.c
The cast is unnecessary in C and should be removed to avoid clutter.
This is dependent on #781 and should be rebased after that one is merged.
=> [client] remove all casts around malloc

common/src/platform/windows/windebug.c
This avoids problems when the error message we are told to format contains inserts like `%1`.
See https://devblogs.microsoft.com/oldnewthing/20071128-00/?p=24353 for details (or for fun).
=> [common] windebug: pass FORMAT_MESSAGE_IGNORE_INSERTS to FormatMessage

client/src/app.c, client/src/config.c, client/src/kb.c, client/src/kb.h, client/src/keybind.c, client/src/overlay/help.c
We are using Linux key codes defined in input-event-codes.h, not XFree86
stuff.
=> [client] kb: rename key code arrays from xfree86_* to linux_*

client/renderers/EGL/shader/downscale_lanczos2.frag
Using 4x4 means that some pixels will be outside of the lanczos window. The
ideal lanczos function should in fact be zero in those areas, so we shouldn't
waste time processing those pixels.
I can't notice any difference in the results.
=> [client] egl: look at 3x3 around the pixel instead of 4x4

client/CMakeLists.txt, cmake/CheckSubmodule.cmake, host/CMakeLists.txt, obs/CMakeLists.txt
This gives users a command to run that will automagically fix the submodule
situation, and should reduce the amount of support requests.
=> [all] cmake: tell users to clone submodules when they haven't

client/include/egl_dynprocs.h, client/renderers/EGL/texture_util.c, client/src/egl_dynprocs.c
On some implementations (e.g. llvmpipe), the function can only be queried via
`eglGetProcAddress`.
=> [client] egl: dynamically import glBufferStorageEXT

client/renderers/EGL/egl.c
EGL_CONTEXT_OPENGL_DEBUG is only defined in EGL 1.5, and therefore, we should
not be passing it on older versions of EGL.
=> [client] egl: fix context creation on EGL 1.4

client/src/core.c
This PR fixes two annoying issues with guest-side mouse realignment:
1. We no longer display the mouse before the realignment is finished. This avoids showing the mouse briefly at the old position when reentering the window.
2. We no longer warp the hose cursor if the guest cursor is not visible. This avoids warping the host cursor when the guest-side warp has not finished, which will result in the host cursor exiting at the wrong position if it exits at that moment.
=> [client] spice: fix mouse realignment issues

client/src/app.c, client/src/main.h
imgui really hates it when we update the modifier key state after `igNewFrame`.
The result is:
void ImGui::ErrorCheckEndFrameSanityChecks(): Assertion `(key_mod_flags == 0 || g.IO.KeyMods == key_mod_flags) && "Mismatching io.KeyCtrl/io.KeyShift/io.KeyAlt/io.KeySuper vs io.KeyMods"' failed.
Therefore, we buffer the modifier state information and update it in the IO object right before we call `igNewFrame`.
=> [client] imgui: fix modifier key modification race

host/platform/Linux/capture/CMakeLists.txt, host/platform/Linux/capture/XCB/src/xcb.c, host/platform/Linux/capture/pipewire/CMakeLists.txt, host/platform/Linux/capture/pipewire/src/pipewire.c, host/platform/Linux/capture/pipewire/src/portal.c, host/platform/Linux/capture/pipewire/src/portal.h
It works, with the following limitations:
1. user is forced to select the monitor through platform-specific mechanisms every time the client starts.
2. cursor is composed onto the screen, and no position can be reported.
=> [host] pipewire: implement basic capture

client/renderers/EGL/postprocess.c, common/CMakeLists.txt, common/include/common/vector.h, common/src/vector.c
Due to the difficulty of swapping elements with `struct ll`, I created a vector common type (based on C++'s `std::vector`) and switched the storage. There are likely other places that could benefit from this new type (e.g. `EGLImage` storage in `texture_dmabuf.c`), and those will be switched over later.
=> [client] egl: allow postprocessing filters to be reordered by dragging

client/renderers/EGL/postprocess.c
This avoids duplicating the entire array of filters.
=> [client] egl: simplify filter moving logic with memmove

common/src/option.c
=> [common] option: return NAN when float option doesn't exist

client/renderers/EGL/postprocess.c, common/include/common/option.h, common/src/option.c
This new function dumps all options marked as preset instead of dumping
individual sections. This should allow filter options to not be all grouped
into the [eglFilter] section.
=> [common] option: change option_dump to option_dump_preset

client/renderers/EGL/postprocess.c
This PR makes selecting a preset load it, and changes "Create preset" to "Save preset as...". Also fixed a bug that results in preset duplication when saving over a preset.
=> [client] egl: make preset UI more intuitive

client/src/app.c, client/src/main.h
Currently, this is visible through how fast the cursor blinks, with it blinking faster at higher refresh rates. This commit makes the timing consistent.
=> [client] imgui: run animations at consistent speeds

client/src/app.c, client/src/main.c
The translucent white modal background sort of cancels out the dark
background we apply to the overlay, which is undesirable. It should
instead further darken the background.
For consistency, we now use igGetColorU32Col(ImGuiCol_ModalWindowDimBg)
to draw the overlay background, to avoid hardcoding the same colour in
multiple places.
=> [client] imgui: use consistent modal background colours

client/src/main.c, common/CMakeLists.txt, common/include/common/cpuinfo.h, common/src/cpuinfo.c, common/src/platform/linux/CMakeLists.txt, common/src/platform/linux/cpuinfo.c, common/src/platform/windows/CMakeLists.txt, common/src/platform/windows/cpuinfo.c, host/src/app.c
=> [all] print out CPU information on startup

client/renderers/EGL/CMakeLists.txt, client/renderers/EGL/desktop.c, client/renderers/EGL/filter.c, client/renderers/EGL/filter.h, client/renderers/EGL/filter_downscale.c, client/renderers/EGL/filter_ffx_cas.c, client/renderers/EGL/filter_ffx_fsr1.c, client/renderers/EGL/postprocess.c, client/renderers/EGL/postprocess.h, client/renderers/EGL/shader/basic.vert
This saves a lot of GPU power for partial updates. Running testufo with
lanczos downscaling and FSR upscaling consumed over 90 W, but with this
commit, consumed only 75 W.
=> [client] egl: make filters damage aware

client/src/main.c
Previously, all progress made during sleep is reset, so if the thread keeps
getting interrupted before the sleep finishes, the sleep will never complete.
=> [client] main: correctly handle EINTR from nanosleep

client/displayservers/Wayland/wayland.c, client/src/main.c
Since the display server owns a graph, it was necessary to move the overlay
graphs destruction so that it happens after display server destruction.
=> [client] wayland: free presentation objects

client/src/core.c
This prevents attempts to grab the pointer after the guest side warp
finishes if the pointer has left the window in the meantime. On Wayland,
this would result in the pointer moving to the middle of the window when
the confine is created.
=> [client] spice: stop if pointer left during guest warp

.github/workflows/build.yml, host/platform/Windows/installer.nsi
The host is a 64-bit application, so requiring 64-bit Windows isn't an
issue. However, not using 32-bit installers has an advantage: we don't
need to require WoW64.
Please test [looking-glass-host-setup.zip](https://github.com/gnif/LookingGlass/files/7202713/looking-glass-host-setup.zip) (requires bleeding edge client).
=> [host] installer: build 64-bit NSIS installers

host/platform/Windows/capture/NVFBC/src/nvfbc.c
If the wait times out, we used to simply restart the loop, which causes it to check `this->stop` and exit if set to `true`. However, `nvfbc_stop` already calls `lgSignalEvent`, which would wake up the pointer thread to perform the check, so there is no need to set a timeout on the wait.
=> [host] nvfbc: avoid waking up pointer thread for no reason

client/displayservers/X11/x11.c
The Linux OpenGL ABI does not guarantee that glXSwapIntervalEXT will be
exported statically from any library, and indeed on some systems this
function does not link at load time, e.g. with amdgpu-pro. All other
GLX functions that we use are from GLX 1.0, which is guaranteed to be
exported statically.
This commit solves this issue by using glXGetProcAddressARB to load the
function. Note that only the ARB version of glXGetProcAddress is
guaranteed to exist by the Linux OpenGL ABI, which is why we must use
it.
=> [client] x11: load glXSwapIntervalEXT dynamically

client/include/egl_dynprocs.h, client/include/eglutil.h, client/renderers/EGL/egl.c, client/renderers/EGL/texture_dmabuf.c, client/src/egl_dynprocs.c
The dmabuf path is optional, so we shouldn't require those functions to link our program.
In this PR, we also switch to using the prototypes defined in EGL and GLES headers instead of defining them ourselves.
=> [client] egl: use eglCreateImage and eglDestroyImage indirectly

client/CMakeLists.txt, client/include/gl_dynprocs.h, client/renderers/OpenGL/opengl.c, client/src/gl_dynprocs.c, client/src/main.c
This PR adds the `gl_dynprocs` module, which is similar to `egl_dynprocs`, except for OpenGL functions. We then add a check for the extensions that we need and then calls the functions indirectly through `gl_dynprocs`.
This should improve compatibility with older versions of OpenGL, as we now fallback to the ARB extensions if possible, and in the case of `glGenerateMipmap`, we can handle the function not existing at all.
=> [client] opengl: indirectly access non-OpenGL 1.3 functions 

.github/workflows/build.yml, gl-check
This prevents us from exceeding the minimum GL/EGL versions that we are targetting or forced to use indirection for due to lack of guarantee in the ABI.
=> [client] ci: check for improper usage of GL functions

client/src/gl_dynprocs.c
TabNine autocompleted the function too hard.
=> [client] opengl: fix getProcAddressGL2 naming

common/include/common/time.h
Time values of scientific notation replaced with expanded values
and `tv_nsec` simplified with modulo
=> [common] time: fixed time values in nsleep

client/renderers/EGL/desktop.c
This appears to eliminate artifacts related to non-full screen paints
due to precision errors with the nearest filter.
=> [client] egl: use linear filter when not scaling

cmake/CheckSubmodule.cmake
This runs `git submodule summary` and fails the build if there is any
output. For developers, use `cmake -DDEVELOPER=yes` to bypass this
check.
=> [all] cmake: fail if wrong submodule version is checked out

client/displayservers/Wayland/cursor.c, client/displayservers/Wayland/input.c, client/displayservers/Wayland/wayland.c
This is a bug reported by @Xyene, who should confirm it has fixed his issue.
=> [client] wayland: make cursor change work without wl_pointer

doc/module.rst
Latest versions of QEMU are running out of PCIe mapping
through libvirt as the commandline device is mapping
ivshmem before other root devices.
Use JSON style configuration in the commandline block.
JSON arguments are loaded after all regular ones
and will guarantee to get loaded after all other libvirt mapped
PCIe devices.
=> [doc] module: Modify libvirt commandline block to use JSON

doc/module.rst
Older libvirt and QEMU require older style config
so put it back with version instructions.
=> [doc] module: Bring back older style XML

client/src/core.c
`g_state.posInfoValid` could become valid after the guest reports the
cursor position, in which case we did not show the cursor until another
update occurs.
This commit eliminates the race by performing the update when
`g_state.posInfoValid` becomes true.
=> [client] input: fix race between window size and guest cursor

.gitignore
This prevents accidental commits of the compiled spellchecker.
=> [all] gitignore: ignore __pycache__ and *.py[co]

.github/workflows/build.yml, host/platform/Windows/installer.nsi
To use this, run `makensis` with `-DIVSHMEM` with the driver files in the
`ivshmem` subdirectory under the build directory.
Preview:
=> [host] installer: add ability to install IVSHMEM driver

host/platform/Windows/installer.nsi
This should make the installer look less blurry on high DPI displays.
Here's an example on 125% scale:
=> [host] installer: enable DPI awareness

doc/conf.py
We prefer the VERSION file if available, otherwise falling back to
querying version directly from git.
=> [doc] automatically detect version

.github/workflows/build.yml, README.md, doc/conf.py
From https://github.com/readthedocs/sphinx_rtd_theme
Before this is merged, the debian package `python3-sphinx-rtd-theme` should be installed on the build server
=> [docs] all: Switch to sphinx-readthedocs-theme

doc/conf.py
We got the gist of it, but in the end, didn't git it right.
=> [doc] conf: Fix typo in release git-describe command

host/platform/Linux/capture/pipewire/src/pipewire.c
I recently added little-endian 10-bit colour formats to PipeWire, which
is what we actually use. The old `r210` format is big endian.
=> [host] pipewire: use new format for 10-bit colour

doc/build.rst
=> [doc] build: Fix apt command overflowing page

host/src/app.c
This makes it much less painful to develop the host, as sometimes it
hangs and ^C doesn't work.
=> [host] app: support force quitting

host/platform/Windows/capture/DXGI/src/d3d11.c
`DEBUG_ASSERT(!this)` in `d3d11_create` is firing on the second
instantiation because we are not clearing `this` in `d3d11_free`.
=> [host] dxgi: fix d3d11 assertion failure

host/platform/Windows/capture/DXGI/src/dxgi.c
The buffer input sizes to the `IDXGIOutputDuplication` methods are measured
in bytes. This dramatically increases the number of dirty/move rects that
can be handled.
=> [host] dxgi: fix frame damage method parameters

module/kvmfr.c
The `DMA_BUF` namespace was introduced in https://github.com/torvalds/linux/commit/16b0314aa746be6c84c0bc6eca9dde0dce2e99df
Fixes the following error:
```
MODPOST /build/source/module/Module.symvers
ERROR: modpost: module kvmfr uses symbol dma_buf_fd from namespace DMA_BUF, but does not import it.
ERROR: modpost: module kvmfr uses symbol dma_buf_export from namespace DMA_BUF, but does not import it.
```
=> [module] fix compile on 5.16

client/renderers/EGL/texture_buffer.c
On my machine (Intel UHD Graphics 770), texture processing occasionally
(about 5% of the time) takes more than 20ms (the highest I have seen is
around 32ms) when the host resolution is 2560x1440. This results in the
frame being discarded and the client displays a stale image. Increase the
timeout to 40ms.
=> [client] egl: increase texture processing timeout

client/src/core.c, client/src/main.h
This prevents LGMP_ERR_QUEUE_FULL from happening with high polling rate
mice, which is caused by receiving many more mouse events while the
guest cursor warps, triggering more warps.
=> [client] input: avoid reentrancy when realigning guest cursor

client/src/kb.h, client/src/keybind.c, client/src/main.c, client/src/main.h
These are implemented as ScrollLock+Up/Down for volume up and down, and
ScrollLock+M to toggle audio mute. These should prove useful especially
when Looking Glass now supports streaming audio, and the volume is
defined in the guest and set on the output stream.
=> [client] spice: allow volume control keys to be sent to the guest

client/src/kb.c
These include Volume Up, Volume Down, Mute, Play/Pause, Stop, Next Track, and Previous Track.
I discovered this on accident when messing around with #934.
I tried adding these as ScrLk shortcuts alongside the shortcuts added by that PR, to effectively let you passthrough the keys. So pressing ScrLk+Mute would toggle mute, ScrLk+VolumeUp would press Volume Up, etc.
It wasn't working until I added this code to `kb.c`, but when I did that, the keys themselves were working just fine in capture mode, so I didn't need the ScrLk keybinds after all.
(Later, I added the multimedia keys Play/Pause, Stop, Next Track, and Previous Track)
Added @quantum5 as co-author because his PR is what made me look at this, and the PS2 scancodes were lifted from his PR.
=> [client] Add support for some multimedia keys in capture mode

doc/build.rst
Webedit because I'm super sleepy and don't want to turn on my laptop.
Just a future proofing warning so the rule of the Reqired Dependencies section is shown to prospective future editors and developers.
I don't yet know if this will show up on the rendered html or not, I followed https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#comments so it should be visible in the source only.
=> [doc] build: Add source comment for listing deps

client/src/core.c
This is only done in non-capture mode to avoid messing up games.
Also, added a redraw after warping. This is because turning off overlay does not involve mouse movement, which means the renderer is not notified of the new cursor position, and thus exposing the fact that the guest cursor is rendered in the wrong location.
=> [client] overlay: realign cursor when turning off overlay

host/src/app.c
This allows the Linux host to start.
=> [host] app: don't read from UUID if none is returned

host/platform/Windows/capture/NVFBC/src/nvfbc.c
To avoid client showing `Using    : NVFBC (NVidia Frame Buffer Capt`.
This happens because the string is truncated to 31 characters to fit in the `char capture[32];` member of `KVMFRRecord_VMInfo`.
=> [host] nvfbc: shorten nvfbc_getName() result

client/audiodevs/PipeWire/pipewire.c, client/audiodevs/PulseAudio/pulseaudio.c, client/include/interface/audiodev.h, client/src/audio.c
The target latency is now based upon the device maximum period size (which may be configured by setting the `PIPEWIRE_LATENCY` environment variable if using PipeWire), with some allowance for timing jitter from Spice and the audio device.
PipeWire can change the period size dynamically at any time which must be taken into account when selecting the target latency to avoid underruns when the period size is increased. This is explained in detail within the commit body.
=> [client] audio: tune target latency

.github/workflows/build.yml, client/displayservers/Wayland/CMakeLists.txt, client/displayservers/Wayland/activation.c, client/displayservers/Wayland/registry.c, client/displayservers/Wayland/wayland.c, client/displayservers/Wayland/wayland.h, client/displayservers/X11/x11.c, client/include/interface/displayserver.h, client/src/main.c
In a future patchset, this will allow us to plumb activation requests from the guest up to the host.
Example of what this looks like in Sway:
Currently, we request activation when we obtain a frame from LGMP for the first time.
Window activation is implementable for X11, but I've not done so in this PR.
=> wayland: implement window activation via xdg-activation

client/src/main.c, common/include/common/KVMFR.h, host/include/interface/platform.h, host/platform/Linux/src/platform.c, host/platform/Windows/src/platform.c, host/src/app.c
This PR depends on https://github.com/gnif/LookingGlass/pull/950, and implements ferrying guest activation requests to host activation requests.
Currently implemented only for Windows guests.
=> [host] windows: plumb guest activation request to host

client/renderers/EGL/desktop.c, client/renderers/EGL/texture_buffer.h
There was an unused sampler in `TextureBuffer`, any time it was bound it used the `base->sampler` instead.
The real point of this, however, is the sampler in the EGL Desktop. If I understand correctly, the desktop doesn't need its own sampler. There is already an identically configured one in the `desktop->texture`.
For some reason, using the texture sampler fixes a black screen issue caused by f0ea882 (where the separate desktop sampler was added) with my GTX 660 using the 470.86 driver. Maybe hitting some limit for how many samplers can be allocated?
=> [client] egl: remove extra samplers

client/audiodevs/PipeWire/pipewire.c, client/audiodevs/PulseAudio/pulseaudio.c, client/include/interface/audiodev.h, client/src/audio.c
- Update PureSpice for draining change
- Increase startup latency to avoid underruns, particularly at very low latency settings
- Keep device open for a while after playback to reduce startup latency if another playback is started shortly afterwards
=> [client] audio: more tuning

.github/workflows/build.yml, host/platform/Linux/capture/CMakeLists.txt
Since the client already depends on PipeWire by default, there is no
reason why the host shouldn't.
=> [host] linux: build with PipeWire by default

client/src/audio.c, common/src/appstrings.c
The actual time between opening the device and the device starting to pull data can range anywhere between nearly instant and hundreds of milliseconds. To minimise startup latency, open the device as soon as the first playback data is received from Spice. If the device starts earlier than required, insert a period of silence at the beginning of playback to avoid underrunning. If it starts later, just accept the higher latency and let the adaptive resampling deal with it.
=> [client] audio: open device earlier

client/audiodevs/PulseAudio/pulseaudio.c, client/displayservers/X11/clipboard.h, client/include/interface/displayserver.h, client/src/config.c, client/src/config.h, client/src/main.c, client/src/overlays.h, common/include/common/ivshmem.h, common/include/common/ll.h, common/include/common/sysinfo.h, host/CMakeLists.txt, host/include/interface/capture.h, host/platform/Linux/capture/XCB/src/xcb.c, host/platform/Linux/capture/pipewire/src/pipewire.c, host/platform/Windows/capture/DXGI/src/d3d12.c, host/platform/Windows/capture/DXGI/src/dxgi.c, host/platform/Windows/capture/NVFBC/src/wrapper.h, host/platform/Windows/include/windows/mousehook.h
`-Wstrict-prototypes` is not yet enforced for the client because it depends on cimgui, whose code generation scripts don't currently generate compatible code.
=> Build with -Wstrict-prototypes

client/src/audio.c
The best quality resampler has an intrinsic latency of about 3ms, and the processing itself takes another 1-2ms per 10ms block. The faster setting has an intrinsic latency of about 0.4ms, with about 0.04ms processing time. This makes for an overall saving of about 4ms, with negligible loss in quality.
=> [client] audio: reduce resampler latency

client/src/audio.c, client/src/config.c
The current minimum target latency is partially based upon the default qemu behaviour whereby audio packets are delivered in a sawtooth pattern, with packet timestamps drifting between 5ms above and below the measured clock. This 5ms error is baked into the minimum target latency to avoid underrunning.
This sawtooth pattern can be reduced by specifying a lower timer period in the qemu configuration, so remove it from the hardcoded minimum latency and add it to the default configurable buffer latency instead. This allows users that have configured their VM appropriately to reduce the overall latency.
=> [client] audio: reduce hardcoded minimum latency

client/CMakeLists.txt, client/src/kb.c
This should be the last of these PRs.
https://github.com/cimgui/cimgui/pull/197 landed, so pull in the latest cimgui. We were on 1.86, so fix compilation for 1.87.
=> Build client with -Wstrict-prototypes

host/platform/Windows/capture/DXGI/src/d3d12.c, host/platform/Windows/capture/DXGI/src/dxgi.c
The usleep() call lets d3d12 match the sleep calls of d3d11 while
maintaining the current millisecond-scale sleep interface in the
configuration file.
=> [host] dxgi: add microsecond-scale sleep capability to d3d12

client/audiodevs/PipeWire/pipewire.c, client/include/app.h, client/src/app.c, client/src/audio.c, client/src/config.c, client/src/core.c, client/src/main.h, client/src/overlay/msg.c, client/src/overlay/msg.h
This prevents rogue Windows applications from spying on you. To disable the prompts and always grant access, use `audio:micAlwaysAllow`.
This PR also includes the following fixes:
* Fix a bug in `core_updateOverlayState` that breaks message boxes when they show up the second time.
* Fix a type issue with `app_msgBoxClose`. It should not be taking a pointer to a handle. This bug was masked because it was declared as an alias of `void *` instead of pointer to a `struct`.
* Fix a bug with PipeWire backend not stopping recording
=> Add a confirmation dialog before we start recording

client/src/audio.c
If a recording is already in progress, we should not prompt again.
=> [client] audio: avoid prompting when changing record format

client/audiodevs/PipeWire/pipewire.c
pw_stream_get_time() is deprecated in PipeWire 0.3.50. Use pw_stream_get_time_n() instead based on PipeWire
library version.
As of this writing the PipeWire master branch is still at 0.3.49, but the deprecation commit has been merged about a week ago, so this patch will not solve build issues until master is updated to 0.3.50. To build from PW master for now we can turn off Werror for deprecations `CFLAGS='-Wno-error=deprecated-declarations' cmake ..`
=> [client] audio/pw: pw_stream_get_time() deprecated

client/src/audio.c, client/src/config.c, client/src/main.h
The new `audio:micDefault` takes three options: `prompt`, `allow`, `deny`. This dictates the default action taken when an application opens the microphone.
With #991, these defaults can be changed after the fact.
=> [client] audio: replace audio:micAlwaysAllow with audio:micDefault

client/src/overlay/graphs.c
The Wayland display server has a graph for presentation times, but the backend shuts down after the overlays, so calling `overlayGraph_unregister` causes memory corruption. We can avoid this problem by making unregister a noop after all graphs have been freed.
This is safe because updating the graph doesn't use the graph handle: instead you update the `ringbuffer` which is owned by the user.
=> [client] overlay/graphs: allow unregistering after shutdown

client/CMakeLists.txt, client/audiodevs/PipeWire/CMakeLists.txt, client/audiodevs/PulseAudio/CMakeLists.txt, client/displayservers/Wayland/CMakeLists.txt, client/displayservers/X11/CMakeLists.txt, client/renderers/EGL/CMakeLists.txt, client/renderers/OpenGL/CMakeLists.txt, common/CMakeLists.txt, common/src/platform/linux/CMakeLists.txt, common/src/platform/windows/CMakeLists.txt, host/CMakeLists.txt, host/platform/Linux/CMakeLists.txt, host/platform/Linux/capture/XCB/CMakeLists.txt, host/platform/Linux/capture/pipewire/CMakeLists.txt, host/platform/Windows/CMakeLists.txt, host/platform/Windows/capture/DXGI/CMakeLists.txt, host/platform/Windows/capture/NVFBC/CMakeLists.txt, obs/CMakeLists.txt
This PR standardizes cmake indentation to 2 spaces.
It also makes it so that `-Wstrict-prototypes` is passed for C only to avoid this warning:
```
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
```
=> [all] cmake: standardize indentation and remove warnings

.github/workflows/build.yml
With checkout v1, it checks out all the repository history, which takes
~20 seconds to complete with all the submodules that we have. With v2,
takes <10 seconds to complete the checkout by virtue of checking out
only the latest commit.
For some cursed reason, spell check starts failing if docs uses v2
checkout, but doesn't fail if it uses v1.
=> [ci] switch to checkout v2

client/displayservers/Wayland/gl.c
Certain window managers give us a scale before it gives us a size.
This PR makes the Wayland backend avoid passing a zero size to `wp_viewport_set_source`, which is a protocol error.
=> [client] wayland: deal getting scale before size

client/displayservers/Wayland/gl.c
The intention has been to keep `wlWm.needsResize` true when skipping resize, but I accidentally negated the value.
=> [client] wayland: fix infinite resize loop

.github/CODEOWNERS
This way I should be notified for changes that interact with this directory.
I would need to be added as a collaborator, which would give me [some inseparable rights and access](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/permission-levels-for-a-personal-account-repository#collaborator-access-for-a-repository-owned-by-a-personal-account) outside of the scope of just code owner.
=> Add myself to CODEOWNERS for docs/

client/displayservers/Wayland/input.c
Note that `xkb scan code = linux scan code + 8`.
=> [client] wayland: correctly convert scan codes to numbers

client/displayservers/Wayland/wayland.c, client/displayservers/X11/x11.c, client/include/interface/displayserver.h, client/src/main.c
This commit makes it show a prettier error message when no display server is available, including the display servers compiled. This replaces the old assert.
Example output:
```
[E] 572277145932              main.c:1167 | lg_run                         | No display servers available, tried:
[E] 572277145934              main.c:1169 | lg_run                         | * Wayland
[E] 572277145935              main.c:1169 | lg_run                         | * X11
```
=> [client] main: better error when no display server is available

client/src/audio.c, client/src/keybind.c, client/src/main.c, client/src/main.h
This makes it possible to change the default action taken the next time an application tries to open the microphone without restarting the client.
=> [client] keybind: add ScrollLock+C to toggle microphone defaults

client/displayservers/Wayland/clipboard.c
There is no action to be taken by the Looking Glass client, but a handler needs to exist as certain other Wayland clients chooses to
send this message for copy-paste operations despite the fact it's supposed to be used for drag-and-drop negotiation.
=> [client] wayland: handle wl_data_source.target action

client/renderers/EGL/egl.c, client/src/app.c, client/src/main.c, client/src/main.h, client/src/render_queue.c, client/src/render_queue.h
This PR allows "hardware" cursors on the Spice display to be shown.
Both RGBA and monochrome cursors are tested.
=> Add spice cursor channel support

client/renderers/EGL/egl.c
Without this step, the cursor with be transformed for rendering the spice cursor, not the IVSHMEM cursor.
=> [client] egl: recalculate mouse position when toggling spice

client/displayservers/Wayland/input.c
This fixes the following crash when attempt to toggle capture at the right after closing the overlay:
zwp_pointer_constraints_v1@12: error 1: a pointer constraint with a wl_pointer of the same wl_seat is already on this surface
=> [client] wayland: fix attempt to confine when pointer is locked

doc/usage.rst
Note that ```**``looking-glass-client``**``` is not valid syntax.
=> [doc] usage: fix command name bolding

doc/usage.rst
This uses syntax highlighting for the config file and also documents the ; comment character.
=> [doc] usage: improve ini syntax documentation

obs/lg.c
Small oversight from my last PR that was causing a crash on properties save when clicking "Cancel" in the plugin properties window.  Turns out the frame/pointer threads were being mismanaged in deinit() due to calling the incorrect function.
=> [obs] Fix function call causing crash on lgUpdate

client/src/audio.c
This is rare and I'm not sure what causes it, but PipeWire sometimes uses a larger period size than requested for no obvious reason (e.g., we could request a period size of 512, but PipeWire uses 2048 anyway). This causes us to stay in a permanent state of underrunning because the target latency is too low.
With this change, we use the actual device period in the target latency calculation if it is larger than the expected maximum. We may still get some glitches at the beginning of playback (because the startup latency is based upon the expected maximum period size), but it will recover after a few seconds as it adjusts to the new target latency.
=> [client] audio: use actual device period if larger than expected maximum

AUTHORS, client/displayservers/X11/clipboard.c, client/src/app.c
With -Wstrict-prototypes on non-protyped functions are deprecated and functions must include a void parameter if they do not take parameters.
=> Remove non-prototype function declarations

host/platform/Windows/src/platform.c, host/src/app.c
This PR does two things:
* clarify that config file not found is not fatal to prevent users from thinking this is the problem they are facing.
* log to stderr that logs will continue in log file on Windows to prevents users from posting the stderr as if it's the only output.
This should be merged for B6 to reduce support volume.
=> [host] improve logging to avoid confusion

client/displayservers/Wayland/shell_xdg.c, client/displayservers/Wayland/wayland.h
This should allow `win:autoResize` to work on Wayland when the compositor supports such an operation.
=> [client] wayland: implement window size setting for xdg-shell

doc/requirements.rst, doc/troubleshooting.rst
Added Connected Display subsection to requirements.rst to so we can link to it easier, and link to it from the questionably troubled troubleshooting question.
Actually, rewrites that question to redirect back to the requirements.
=> [doc] troubleshooting: Rewrite missing desktop

.github/workflows/build.yml
Uses the Debian/Ubuntu package for sphinxcontrib-spelling rather than from pip. This fixes the issue by virtue of being an older version. I think we should prefer these packages anyway for stability.
This issue looks to have been caused by sphinxcontrib-spelling needing `docutils >= 0.18.1` but not declaring that as a requirement (see sphinx-contrib/spelling#212). The current `ubuntu-latest` appears to feature 0.17.1:
[![Screenshot_20230404_172738](https://user-images.githubusercontent.com/5211576/229824645-b411a955-a6ba-4b01-8e68-3445d93a4d83.png)](https://github.com/gnif/LookingGlass/actions/runs/4608362713/jobs/8144023739#step:4:36)
[Build test](https://github.com/JJRcop/LookingGlass/actions/runs/4608732839/jobs/8144906062)
=> [github] build: Use debian package for sphinxcontrib-spelling

.github/CODEOWNERS
Made an embarassing typo.
It's doc not docs
=> [github] CODEOWERS: Fix typo stopping JJRcop owning /doc/

common/src/option.c
Oops on command line parser logic argv counter
=> [common] options: Fix regression in option parsing logic

module/dkms.conf, module/kvmfr.c
Remove second parameter from class_create since Linux >= 6.4 uses data from struct instead supplied from previous calls.  Draft PR until I can get this tested properly.
=> [module] Fix build on Linux 6.4 (fixes #1075)

doc/faq.rst
Update link from https://gitlab.gnome.org/jadahl/libdecor to https://gitlab.freedesktop.org/libdecor/libdecor
Change package name from `libdecor` to `libdecor-0-dev` to help those that may install the non-devel dependency.
=> Update libdecor source link in FAQ and package name to dev package

doc/conf.py, doc/html_unescape.py, doc/usage.rst
Fixes no-break space by adding a new html_unescape extension to the docs, which runs Python's `html.unescape` on source files before Sphinx renders them.
This lets us use HTML references like `&nbsp;` in the docs, which get turned into the real characters as Sphinx is reading the files to render them. The source files are not affected, this only happens when rendering.
I have also published this extension in my own name under a different license (the same one Sphinx uses) for others to use:
https://github.com/JJRcop/sphinxcontrib-html_unescape
=> [doc] html_unescape: Create html.unescape extension and use it for no-break space

client/renderers/EGL/shader/convert_bgr_bgra.frag, client/renderers/EGL/texture_framebuffer.c, host/platform/Windows/capture/DXGI/src/d3d11.c, host/platform/Windows/capture/DXGI/src/dxgi.c, host/platform/Windows/capture/DXGI/src/pp/rgb24.c
Copying my comments motivating this approach from Discord for posterity:
> we can make a slight modification to the HLSL conversion shader to never consider data from row (i+1) when converting row i
> (this can only happen for the alpha channel of the rightmost pixel on a row anyway)
> so this would have the effect of making the height of the output texture be the same as the input, but the width be round(inputWidth * 3 / 4, 4) / 4 
> and we could perform a single CopySubResource per damage rect as we have before
> and should not have any implications for the guest, they're still seeing the packed data they expected to see
> we only need to do the 1 CopySubResource per row of damage rect thing if we allow the alpha channel of the last pixel on row i to encode the red channel of the first …
=> Implement damage-aware copies for RGB24-packed data

doc/build.rst
Also:
- Add link to warning (#dont-build-the-host)
=> [doc] build: Move NvFBC note into don't build warning

client/displayservers/Wayland/desktops/libdecor/libdecor.c
This likely fixes an issue surrounding full screen not being honoured when creating the window when using the libdecor code, but I have received no confirmation on Discord.
=> [client] wayland: honour fullscreen and maximize in libdecor

doc/ivshmem_kvmfr.rst, doc/words.txt
Restructure the module libvirt XML setup instructions so users understand how to change the XML namespace and that changes need to be atomic.
=> [doc] Update module libvirt setup

client/audiodevs/PipeWire/pipewire.c
Some applications require the setting of pipewire's `application.name` to properly identify the app's audio. Adding the same app name as the node name to the client.
=> [client] pipewire: Add pipewire application name

host/src/app.c
While resuming from hibernation lgmpTimer may transition app.state to APP_STATE_REINIT_LGMP. Sometimes the transition is lost if the app_main processing loop also changes app.state simultaneously. This seems to occur frequently with the hibernation use case.
Separate lgmp timer state into its own enum. Move resulting app.state transitions to the app_main loop so they are serialized.
=> [host] app: fix app state race in lgmpTimer thread

client/src/overlay/status.c
The renderer contains an optimization to skip ImGui if there is nothing to show, but the status overlay always returns a damage rect, even if it didn't draw anything, so the optimization can never take effect.
=> [client] overlay/status: don't return damage rect if nothing was drawn

client/src/overlay/msg.c, common/include/common/ll.h, common/src/ll.c
If an overlay is closed with `overlayMsg_close`, the message can be freed while it is still being used by `msg_render`, resulting in a segfault. Lock the message list for the duration of `msg_render` to fix this.
A semi-reliable way to reproduce this is to put a 20ms sleep after the call to `ll_peek_head` in `msg_render`. Use remote desktop to stop the Looking Glass host service, then start the client. The 'host not running' message should appear. Now start the host service. The client will now probably crash somewhere inside `msg_render` because the message it is rendering has been freed by `overlayMsg_close`.
Not sure this is the cleanest approach, but I've taken after the precedence of `ll_forEachNL` by adding some more `nl` methods. Perhaps it would be better to add a new lock in …
=> [client] overlay/msg: fix race condition in render

doc/install_libvirt.rst, doc/requirements.rst, doc/words.txt
Also added link in install_libvirt to the new section.
=> [doc] requirements: Add section encouraging DMABUF use for iGPUs

client/CMakeLists.txt, resources/looking-glass-client.desktop.in
This PR competes with #1011. That was an attempt to ship a .desktop file and icon on Linux which got stalled.
This resolves the stall by only installing the SVG icon, which have had great support on Linux for about a decade.
Gnome Boxes is examples of another KVM app on Linux that only ships an SVG icon.
Because Looking Glass doesn't ship a desktop or icon on Linux, some people are creating their own and in some cases have wrongly selected the ~2500x2500 PNG logo file as their choice, accidentally slowing down their system as their desktop system works to downscale the huge PNG to a reasonable size.
See: https://codeberg.org/dnkl/fuzzel/issues/306
Shipping a proper icon will resolve that.
This also provides two other improvements over #1011:
- The spelling of "Client" is corrected in the …
=> Install .desktop file and SVG icon on Linux

client/audiodevs/PipeWire/pipewire.c
Pipewire now automatically moves non-rt clients into non-rt threads so client-rt.conf is obsolete.
Pipewire will now emit a deprecation warning if a client tries to load RT config properties which LG does.
Stop loading RT properties during context initialization for Pipewire 1.3.81 and newer.
See: https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/24bcacc6195ffbf8e40c9ea1374eb6666252eadc
Reference branch was accidentally removed so this is a re-submit. Please see discussion in https://github.com/gnif/LookingGlass/pull/1174
=>  [client] pipewire: Stop loading properties from client-rt.conf

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml
GitHub switched its issue template to a new workflow. This PR moves the current template to comply with the new structure and also adds a pre-selector that offers links to the forum and discord.
=> [all] Update to new issue template workflow

client/displayservers/Wayland/desktops/libdecor/libdecor.c, client/displayservers/Wayland/desktops/xdg/xdg.c
`libdecor_shellInit` was handling `win:allowResize`but ignoring `win:borderless`, so it did nothing on compositors using libdecor, for example GNOME/Mutter
Conversely, `xdg_shellInit` was handling `win:borderless` but ignoring `win:allowResize`, so it did nothing on compositors using the XDG shell protocol, for example KDE/Kwin, and many others
This Pull Request fixes both issues and now both options work fine on different Wayland compositors.
=> Both Wayland desktops support win:allowResize and win:borderless

.github/workflows/build.yml
This allows forks for whom windows-latest doesn't point to `windows-2025` to build successfully.
=> [host] ci/windows: use explicit windows-2025

idd/LGIddInstall/LGIddInstall.c
Windows 11 does not allow the key to be owned by USER MODE DRIVERS granting the user control via the ACL should resolve this
=> [idd] installer: dont make the reg key owned by USER MODE DRIVERS

idd/LGIddHelper/CWindow.cpp, idd/LGIddHelper/CWindow.h, idd/LGIddHelper/LGIddHelper.vcxproj, idd/LGIddHelper/LGIddHelper.vcxproj.filters, idd/LGIddHelper/main.cpp, idd/LGIddHelper/resource.rc, idd/installer.nsi
This PR makes the IDD helper display a notification icon. To assist in this, the window logic has been refactored into `CWindow` and the application converted to use Unicode for all Windows APIs.
=> [idd] helper: implement notification icon

idd/LGIddHelper/CWindow.cpp, idd/LGIddHelper/CWindow.h, idd/LGIddHelper/main.cpp
This PR improves the window cleanup for the IDD helper and gets rid of the event object, instead just opening the parent process (whose PID is specified as an argument) with `SYNCHRONIZE`.
It also opens separate log files for the IDD helper service and the actual child process to avoid writing to the same file.
=> [idd] helper: some clean up improvements

idd/LGCommon/CDebug.cpp, idd/LGCommon/CDebug.h, idd/LGIdd/Driver.cpp, idd/LGIddHelper/main.cpp
This commit makes `CDebug` use Unicode internally instead of whatever random code page is in use. It also gets rid of the horrible character counting and replaces that with `vasprintf` and `vaswprintf` helpers (partially inspired by Linux) which allocates a buffer.
For `HRESULT` logging, the error code in both hex and decimal are included.
The output is now guaranteed to be UTF-8.
=> [idd] debug: full Unicode handling and log as UTF-8

.gitmodules
gitlab.freedesktop.org has become unreliable over the last year, to prevent the ci pipeline from failing, fall back to the more stable and trusted anongit.
=> [repos] wayland-protocols: swith to anongit.freedesktop.org
