gnif/LookingGlass

client/main.c
This PR adds a description of the borderless fullscreen functionality to the command line help display.
=> Add borderless fullscreen to command line help

host/Capture/DXGI.cpp, host/Makefile, host/MultiMemcpy.h, host/Service.cpp
Not sure if `restart` not being used was intentional or not, I haven't had a chance to try the build yet.
=> Mingw compile fixes

client/main.c
Give a Hint to SDL2 that we are ignoring ALT-F4
=> [client]: ignore Alt-F4 in ignoreQuit mode

CONTRIBUTORS
"wish" was spelled as "whish" in contributors file
=> Fixed typo

client/renderers/OpenGL/opengl.c
buffer overflow loading opengl_options
=> [client] fix buffer overflow in opengl_options

client/CMakeLists.txt
This avoids polluting the source tree.
=> [client] wm/wayland: generate protocol files into the build dir

client/clipboards/Wayland/src/wayland.c
Copying rich text from the guest would be turned into plaintext on the client.
Prior to this change, this would be sent back to the guest, overwriting its
clipboard. This made it impossible to copy rich text inside the guest.
This commit detects such self-copies by checking if the receiver is the
current process, and rejecting it.
=> [client] clipboard/wayland: avoid writing back to guest clipboard

.github/workflows/build.yml, common/src/platform/linux/ivshmem.c, host/platform/Linux/CMakeLists.txt, host/platform/Linux/capture/XCB/src/xcb.c, host/platform/Linux/src/platform.c
After this PR is merged, on every subsequent PR it should say whether the PR builds successfully or not.
Currently, the following components are built:
Note that in 9ff1859dc134e9f3196703296f868040c77a4dd6, `ivshmemInit` and `ivshmemFree` were split from `ivshmemOpen` and `ivshmemClose`, but only for Windows. To fix the build for the linux host, I created stubs, but the same split should be done at a later time.
=> Build pull requests and master with GitHub Actions

host/platform/Windows/src/service.c
The service should now react to host application exit codes.
For the exit codes that demands it, the service will exit instead of
restarting the host.
=> [host] windows: handle defined exit codes in service

.github/workflows/build.yml
Ensure that the host builds properly on Windows machines too.
=> [host] windows: test native build on GitHub Actions

host/platform/Windows/src/service.c
WTSGetActiveConsoleSessionId will return a session even if it's not logged in,
unlike our old GetInteractiveSessionID function. Launching looking glass on
such a console session will allow the login screen to be captured.
Note that WTSGetActiveConsoleSessionId() will return 0xFFFFFFFF if there are
no sessions attached.
=> [host] windows: allow capture of login screen

host/platform/Windows/src/mousehook.c
Basically, this creates a separate thread for the mouse events, and this
thread detects that the desktop has changed (say to the secure desktop),
and unhooks, switches to the new desktop, and then rehooks.
This allows the cursor location to be updated while using NvFBC on secure
desktop and the login screen.
=> [host] windows: make mousehook.c work on secure desktop

.github/issue_template.md
Use link to the new Looking Glass discord server. Also fixed a typo.
=> [all] update discord link for issue template

host/platform/Windows/capture/NVFBC/src/nvfbc.c
When NvFBCToSysCapture reports recreation is required, we return
CAPTURE_RESULT_REINIT, which eventually calls nvfbc_deinit and then
nvfbc_init.
However, the NvFBC object is actually created in nvfbc_create, which
means the NvFBC object is never actually recreated. The result is an
endless cycle of NvFBC asking for recreation. This commonly manifests
as the client waiting endlessly for the host when the guest machine
reboots.
In this commit, the NvFBC object creation is moved into nvfbc_init,
and when recreation is required, it will actually be recreated.
=> [host] nvfbc: move NvFBCToSysCreate into nvfbc_init

host/platform/Windows/capture/NVFBC/src/nvfbc.c
The mouse hook code is very fragile, and we would like to avoid unhooking
and re-hooking as much as possible.
After this commit, this is done only once, and the hook and 1x1 window is
only destroyed upon exit. This, of course, comes with the downside of
the slight performance penalty if the guest machine is used directly while
the host is running and the client is not running.
=> [host] nvfbc: avoid recreating mouse hook and 1x1 window

client/renderers/EGL/help.c
egl_help_set_text and egl_help_render were both accessing bmp->help from
different threads. This creates a race condition in which if the help text
is quickly toggled on and off, it stays on.
This has been fixed with an atomic exchange.
=> [client] egl: fix race condition in help overlay

README.md
* Added new Looking Glass Discord link (keeping VFIO link as well)
* Level1Techs Triage thread replaced with Looking Glass board
=> README.md link maintenance

client/displayservers/Wayland/wayland.c
This new implementation uses a special mimetype to tag data copied from
the guest, instead of using flags. This should make it easier to
implement asynchronous transfers in the future. Also, it's simpler to
understand and less error-prone.
The pid is included in the mimetype in order to distinguish between
different instances of looking glass: you might want to copy between
two different VMs, for example.
=> [client] wayland: better self-copy detection

common/src/platform/linux/ivshmem.c
It used to be the case that you need to create dmabuf for kvmfr devices
to be able to mmap them. But after #457, this is no longer needed.
Directly mmaping the kvmfr device has the advantage of avoiding the
creation of a dmabuf, which has cost (e.g. the list of pages, the
scatterlist, etc.).
This PR should only be merged after #457.
=> [common] ivshmem: do not create dmabuf for simple mmap

module/README.md
An example to make using the module less painful
=> [module] Add client ini example to kernel module readme

.github/workflows/build.yml, host/platform/Linux/capture/XCB/CMakeLists.txt
Install `libxcb-xfixes0-dev` and link against `libxcb-xfixes`.
=> [host] ci: fix build failure

host/platform/Windows/src/service.c
It is usually considered good practice to enable elevated privileges
for the shortest duration possible.
=> [host] service: disable privileges as soon as they are not needed

host/platform/Windows/src/service.c
Instead of converting every SID to string with ConvertSidToStringSidA
and compare it with the magical SID string for local system with strcmp,
we could instead create the local system SID and compare directly with
EqualSid.
=> [host] service: compare SIDs directly without string conversion

obs/lg.c
=> Fix OBS cursor rendering

AUTHORS
Added GitHub usernames for all users that can be found.
=> [all] add AUTHORS file

.github/workflows/pr-check.yml
This PR adds a GitHub Actions workflow that ensures the pull request author's GitHub username is listed in the `AUTHORS` file.
=> [all] check if pull request author is in AUTHORS

common/src/option.c
Before, if the last line of an ini file has no trailing \n, it is ignored.
This commit changes the parser to process such lines.
=> [common] option: handle ini lines without trailing newline

doc/faq.rst
=> [doc] faq: B4-rc2 touchups

host/platform/Windows/capture/DXGI/src/dxgi.c, host/platform/Windows/capture/NVFBC/src/nvfbc.c
Changes:
1. dxgi: correctly mention AcquireNextFrame in help text
2. nvfbc: optimize change detection loop to break out of the entire loop instead of the current row
Also fixed some formatting issues.
=> [host] capture: various fixes to DXGI and NVFBC

client/renderers/EGL/damage.c
This avoids the issues surrounding glMapBuffer and glMapBufferRange in
OpenGL ES.
=> [client] egl: upload damage vertices with glBufferSubData

client/renderers/EGL/egl.c
The boolean option egl:debug is used to control whether we want debug
output or not. This defaults to true to aid in debugging.
=> [client] egl: use debug context and make it configurable

client/displayservers/Wayland/CMakeLists.txt, client/displayservers/Wayland/gl.c, client/displayservers/Wayland/presentation.c, client/displayservers/Wayland/registry.c, client/displayservers/Wayland/wayland.c, client/displayservers/Wayland/wayland.h, client/include/app.h, client/src/app.c, client/src/main.c, client/src/main.h
This PR adds logic to measure the presentation time of every frame, and plots a graph of time between swap and the frame turning into photons.
This also contains logic to support custom graphs in imgui and supersedes #598.
=> [client] wayland: measure presentation time and display swap to photon graph

host/platform/Windows/src/service.c
Since with the service, we are already running as SYSTEM, we don't need
to use dupeSystemProcessToken to get the token for SYSTEM. This removes
the need for having SeDebugPrivilege, SeTcbPrivilege, and
SeAssignPrimaryTokenPrivilege, or otherwise doing sketchy things.
Furthermore, we now only open the token with the privileges we actually
need.
=> [host] service: use SYSTEM token attached to the current process

host/platform/Windows/CMakeLists.txt, host/platform/Windows/src/platform.c
This requires bumping the minimum Windows version to Windows 7, but I
don't think we care about Vista anyways.
=> [host] windows: directly invoke ChangeWindowMessageFilterEx

host/platform/Windows/src/service.c
Instead of Sleep, we can use WaitForSingleObject with a timeout to be
signalled when the service is exiting.
=> [host] service: respond to exit request while sleeping

host/platform/Windows/src/platform.c
This is much less annoying than creating our own thread just to wait on
a single event, then creating another event to signal that thread to exit.
=> [host] windows: use system thread pool to wait for exit event

host/src/app.c
In scenarios where the guest monitor is used as a primary display (for example when combined with the obs client), the unnecessary strain on the GPU/CPU to capture all frames unbounded is excessive.
=> fps limiter option

client/renderers/EGL/egl.c
This tracks the time taken to load the frame buffer into an OpenGL texture.
=> [client] egl: add graph tracking time taken to import frame

common/src/platform/windows/ivshmem.c
We now enumerate all IVSHMEM devices, sort them based on PCI bus, slot, and function numbers, then index from the resulting order. This should be consistent across boots.
To help the user identify the correct IVSHMEM device, we also print the list of IVSHMEM devices on startup.
=> [common] ivshmem: use consistent device numbering on Windows

client/src/app.c, client/src/keybind.c, client/src/main.h
Tasks:
* ~forward keyboard modifiers~ (for later)
* ~forward typed characters~ (for later)
=> [client] imgui: add mode to forward mouse and keyboard input to imgui

doc/install.rst
1. Add new keybindings for damage display and frame timing
2. Add command line options for ImGui UI font name and size
=> [doc] install: Update new keybindings and command line options

client/src/config.c
We look for the client config in $XDG_CONFIG_HOME/looking-glass/client.ini.
This is done because it's more conventional, and also allows us to add
additional configuration files, e.g. for the host.
We fallback to $HOME/.config as is standard, and then as a last resort use
getpwuid(getuid())->pw_dir. This is also recommended by the getpwuid manpage:
> An application that wants to determine its user's home directory should
> inspect the value of HOME (rather than the value getpwuid(getuid())->pw_dir)
> since this allows the user to modify their notion of "the home directory"
> during a login session.
=> [client] config: optionally load config from XDG_CONFIG_HOME

client/renderers/EGL/egl.c
This prevents damage from being overwritten when frames are received
faster than could be rendered.
This implementation cycles between two queues, removing all need for
memory allocation.
=> [client] egl: use queue of damages

client/renderers/EGL/egl.c
There used to be a possible race when a bunch of rectangle is appended, but
the total count is not updated before it's read. Using a lock eliminates
all such races.
=> [client] egl: use a lock for desktop damage to eliminate all races

client/include/overlay_utils.h, client/src/overlay/config.c, client/src/overlay_utils.c, common/include/common/open.h, common/src/platform/linux/CMakeLists.txt, common/src/platform/linux/open.c
* This is only implemented for Linux for now.
* On Windows, `ShellExecute` should be used, but that should be done when it's actually needed so it could be tested.
=> [client] imgui: implement new widget for displaying URLs

host/platform/Windows/capture/NVFBC/src/nvfbc.c
Certain drivers do not support pitches that are not multiples of 128 bytes,
and instead just does some kind of rounding internally. On DXGI, this is not
a problem because the API rounds pixel pitch, but NvFBC does not. This causes
certain resolutions to simply not work with dmabuf, most notably 3440x1440,
which is 1440p ultrawide.
Since we are copying pixels with the CPU anyways, we might as well round the
pitch up to 128 bytes (32 pixels).
=> [host] nvfbc: round pitch to multiple of 128 for dmabuf import

host/platform/Windows/capture/DXGI/src/dxgi.c
This implementation uses a line sweep algorithm to copy the precisely the
intersection of all accumulated damage rectangles, ensuring that every
pixel is copied exactly once, and no pixel is ever copied multiple times.
Furthermore, once a row has been swept, we update the framebuffer write
pointer immediately.
=> [host] dxgi: copy only damaged regions to IVSHMEM

client/renderers/EGL/texture_dmabuf.c
This avoids race conditions in GL drivers when attempting to render and
call glEGLImageTargetTexture2DOES on the same texture.
Also, when using glEGLImageTargetTexture2DOES, we do not need to allocate
storage for textures.
This hasn't crashed in over a day, so it's probably okay?
=> [client] egl: cycle through multiple textures for dmabuf

client/renderers/EGL/CMakeLists.txt
We'd rather use known versions of awk if possible for ease of troubleshooting.
=> [client] egl: prefer gawk and mawk when building shaders

client/displayservers/Wayland/cursor.c, client/displayservers/Wayland/wayland.h, client/displayservers/Wayland/window.c
This makes the cursor less blurry when high DPI is needed.
=> [client] wayland: support high DPI cursors when needed 

client/displayservers/X11/x11.c, client/displayservers/X11/x11.h
I only tested this on Xwayland. While this should work on real X11, I can't be sure that it does.
=> [client] x11: implement keyboard typing and modifiers

doc/build.rst, doc/faq.rst
This has been asked too many times by various people on Discord. I think we should just put it in the documentation.
=> [doc] add documentation about libdecor

client/renderers/EGL/postprocess.c, client/renderers/EGL/texture_dmabuf.c, common/include/common/vector.h, common/src/platform/windows/ivshmem.c, common/src/stringlist.c, common/src/vector.c
This PR allows vectors to be used without double allocation, and also changes stringlist to use vector for storage.
=> [common] vector: improvements and use as backing for stringlist

client/renderers/EGL/filter.h, client/renderers/EGL/filter_downscale.c, client/renderers/EGL/filter_ffx_cas.c, client/renderers/EGL/filter_ffx_fsr1.c, client/renderers/EGL/postprocess.c, common/include/common/option.h, common/include/common/stringlist.h, common/include/common/vector.h, common/src/option.c, common/src/stringlist.c, common/src/vector.c
Progress:
This supersedes #805.
=> [client] egl: implement presets

common/src/platform/windows/cpuinfo.c
The old code will not correctly report the number of threads on CPUs with
more than one processor group, i.e. when there are more than 64 logical
processors (threads).
=> [common] cpuinfo: handle more than 64 threads on Windows

.github/workflows/build.yml, doc/lgspell.py, doc/words.txt
This is based on #825 and spelling errors are fixed in #826 and #827.
=> [client] ci: check --help spelling

common/src/platform/linux/open.c
Sometimes, e.g. when xdg-open has to start the browser, the xdg-open
process can stay around until the browser exits, which freezes the
client. Instead, we should not wait for xdg-open to exit.
However, we can't simply not call wait, as that would leave the
xdg-open process around as a zombie. We could turn off the SIGCHLD
handler, but that's a global solution to a local problem. Instead, we
call setsid and fork again to detach the xdg-open process as if it's a
daemon, and let init take care of the reaping process.
This supersedes #840.
=> [common] open: detach xdg-open instead of waiting for it

client/renderers/EGL/texture_dmabuf.c
Missed this one in the last PR.
=> [client] egl: make the last eglDestroyImage call indirect

doc/obs.rst
regression in bc022c77f461b616eb84b9471cb69ab6746139ef
=> [docs] obs: fix installation instructions grammar

host/platform/Windows/capture/DXGI/src/dxgi.c
Realigned the other messages to match.
=> [host] dxgi: fix typo in debug log message

host/platform/Linux/capture/pipewire/src/pipewire.c
This should provide some useful debug information and report stream
errors.
=> [host] pipewire: report stream state

client/src/main.c, common/include/common/KVMFR.h, common/include/common/cpuinfo.h, common/src/cpuinfo.c, common/src/platform/linux/cpuinfo.c, common/src/platform/windows/cpuinfo.c, host/src/app.c
This is helpful for detecting weird topology configurations.
=> [all] cpuinfo: report CPU socket count

client/displayservers/X11/clipboard.c
=> [client] x11: don't use primary selection for clipboard

host/platform/Windows/src/platform.c
For Windows 10, it so happens that the major.minor is 10.0. This is not usually a given, e.g. on Windows 7 where it would read 6.1, on Windows 8 it would read 6.2, and on Windows 8.1 it would read 6.3.
This is obviously undesirable, so we should just read the `ProductName` from registry if possible. This results in something like:
OS Name: Windows 10 Pro for Workstations (Build: 19043)
=> [host] windows: read ProductName from registry if possible

host/platform/Linux/src/platform.c
Result is something like:
Debian GNU/Linux 11 (bullseye), kernel: Linux 5.14.0-0.bpo.2-amd64 on x86_64
=> [host] linux: allow getting system version

.github/workflows/build.yml, .gitmodules, client/displayservers/Wayland/CMakeLists.txt, cmake/CheckSubmodule.cmake
This should make LG easier to build on less bleeding-edge distros.
=> Submodule wayland-protocols

host/include/interface/platform.h, host/platform/Linux/src/platform.c, host/platform/Windows/src/platform.c, host/platform/Windows/src/service.c, host/src/app.c
Noticed while working on the activation stuff.
=> [host] cleanup some missing (void) parameters

client/audiodevs/PipeWire/pipewire.c
This is as per the PipeWire ALSA plugin [1]. The existing `PW_STREAM_FLAG_RT_PROCESS` flag is misleading and doesn't really have anything to do with real-time priority; it just tells PipeWire to pull data from the application synchronously from its main processing thread. More detail at [2].
[1] https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/f5d47c079e4ed23d0aa2d2f2f4ce19ee720bee1b/pipewire-alsa/alsa-plugins/pcm_pipewire.c
[2] https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2024
=> [client] audio/pw: request real-time priority

client/audiodevs/PipeWire/pipewire.c, client/audiodevs/PulseAudio/pulseaudio.c, client/include/interface/audiodev.h, client/src/audio.c, client/src/config.c, client/src/main.h
=> [client] audio: miscellaneous tweaks

client/CMakeLists.txt, client/include/app.h, client/src/app.c, client/src/audio.c, client/src/config.c, client/src/main.c, client/src/main.h, client/src/overlay/record.c, client/src/overlays.h
This appears as a slowly flashing red dot in the top right corner.
=> Add audio recording indicator

client/src/overlay/status.c
When the window scale goes above the scale the SVGs were rasterized at, we re-rasterize them at the necessary scale for a more crisp appearance.
=> [client] overlay/status: re-rasterize at high DPI when needed

common/src/appstrings.c
Very cheeky but is self-authored :smile:
=> [common] appstrings: Amend blurb for jjrcop with fluff

client/src/main.c
This prevents the flash of spice display when it's not set to mirror in the VM.
=> [client] spice: wait 1 second before attempting to use spice video

doc/usage.rst, doc/words.txt
Also refresh opening paragraph in the *Host usage* section
=> [doc] usage: Add Selecting an IVSHMEM device

client/renderers/EGL/desktop.c
Code now matches the error message.
=> [client] egl: fix desktop render dimensions check

.github/workflows/pr-check.yml
Adds a few steps to the authors job in the pr-check workflow to add a review requesting changes to PRs failing the check.
This review can then be dismissed when they have added themselves.
=> Request changes when authors action fails

idd/LGIddHelper/CConfigWindow.cpp, idd/LGIddHelper/CConfigWindow.h, idd/LGIddHelper/CNotifyWindow.cpp, idd/LGIddHelper/CNotifyWindow.h, idd/LGIddHelper/CStaticWidget.cpp, idd/LGIddHelper/CStaticWidget.h, idd/LGIddHelper/CWidget.cpp, idd/LGIddHelper/CWidget.h, idd/LGIddHelper/CWindow.cpp, idd/LGIddHelper/CWindow.h, idd/LGIddHelper/LGIddHelper.vcxproj, idd/LGIddHelper/LGIddHelper.vcxproj.filters, idd/LGIddHelper/UIHelpers.h, idd/LGIddHelper/main.cpp
The window may be basic and just display the version number, but it has properly high DPI support and widget positioning capabilities.
=> [idd] helper: implement basic config window
